/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Command gen-helm-rbac renders the Helm chart's ClusterRole template from the
// controller-gen output in config/rbac/role.yaml.
//
// The chart cannot simply copy that file: rules for the deprecated workload types
// must sit inside a conditional block so that disabling
// controller.deprecatedWorkloadTypes.enabled strips them. Splitting those rules out
// by hand rots as soon as a kubebuilder marker changes, so it is done here instead
// and wired into `make manifests`.
package main

import (
	"fmt"
	"os"
	"strings"

	rbacv1 "k8s.io/api/rbac/v1"
	"sigs.k8s.io/yaml"

	"sigs.k8s.io/rbgs/api/workloads/constants"
)

const (
	sourcePath = "config/rbac/role.yaml"
	targetPath = "deploy/helm/rbgs/templates/rbac/clusterrole.yaml"
	// chartRoleName is the chart-scoped name; controller-gen emits "controller-role".
	chartRoleName = "rbgs-controller-role"

	conditionStart = "{{- if $deprecatedEnabled }}"
	conditionEnd   = "{{- end }}"
)

// fileHeader is emitted verbatim. The toggle is read exactly as
// deploy/helm/rbgs/templates/manager/manager.yaml reads it, so the RBAC granted here
// and the manager's --enable-deprecated-workload-types flag cannot disagree.
const fileHeader = `---
{{- /*
  Generated by hack/gen-helm-rbac from config/rbac/role.yaml; DO NOT EDIT.
  Run "make manifests" after changing kubebuilder RBAC markers.

  Rules for the deprecated workload types (Deployment, StatefulSet,
  LeaderWorkerSet) are wrapped in a conditional so that disabling
  controller.deprecatedWorkloadTypes.enabled removes them. An unset value counts
  as enabled, matching values.yaml.
*/}}
{{- $deprecatedWorkloadTypes := .Values.controller.deprecatedWorkloadTypes | default dict }}
{{- $deprecatedEnabled := or (not (hasKey $deprecatedWorkloadTypes "enabled")) $deprecatedWorkloadTypes.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ` + chartRoleName + `
rules:
`

// deprecatedResources maps RBAC apiGroup to the resources gated by
// controller.deprecatedWorkloadTypes.enabled. Deriving it from the same constants
// that isDeprecatedWorkloadType switches on keeps the gate from drifting toward
// over-granting. Subresources are matched by their base resource, so
// deployments/status and deployments/finalizers are covered too.
var deprecatedResources = mustGroupResources(
	constants.DeploymentWorkloadType,
	constants.StatefulSetWorkloadType,
	constants.LeaderWorkerSetWorkloadType,
)

// mustGroupResources turns "group/version/Kind" workload types into apiGroup ->
// resource sets, pluralising the kind the way controller-gen does. The inputs are
// compile-time constants, so a malformed one is a build-time bug rather than a
// condition to handle.
func mustGroupResources(workloadTypes ...string) map[string]map[string]bool {
	out := make(map[string]map[string]bool, len(workloadTypes))
	for _, workloadType := range workloadTypes {
		parts := strings.Split(workloadType, "/")
		if len(parts) != 3 {
			panic(fmt.Sprintf("gen-helm-rbac: workload type %q is not group/version/kind", workloadType))
		}
		group, kind := parts[0], parts[2]
		if out[group] == nil {
			out[group] = make(map[string]bool)
		}
		out[group][strings.ToLower(kind)+"s"] = true
	}
	return out
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "gen-helm-rbac: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	raw, err := os.ReadFile(sourcePath)
	if err != nil {
		return fmt.Errorf("read %s: %w", sourcePath, err)
	}

	var role rbacv1.ClusterRole
	if err := yaml.Unmarshal(raw, &role); err != nil {
		return fmt.Errorf("parse %s: %w", sourcePath, err)
	}
	if len(role.Rules) == 0 {
		return fmt.Errorf("%s declares no rules", sourcePath)
	}

	blocks, err := splitRules(role.Rules)
	if err != nil {
		return err
	}
	out, err := render(blocks)
	if err != nil {
		return err
	}
	if err := os.WriteFile(targetPath, out, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", targetPath, err)
	}
	fmt.Printf("gen-helm-rbac: wrote %s from %s\n", targetPath, sourcePath)
	return nil
}

// ruleBlock is a policy rule plus whether it belongs inside the conditional.
type ruleBlock struct {
	rule       rbacv1.PolicyRule
	deprecated bool
}

// splitRules partitions each rule's resources into the always-granted ones and the
// ones gated by the toggle, preserving the input order of both rules and resources.
func splitRules(rules []rbacv1.PolicyRule) ([]ruleBlock, error) {
	var blocks []ruleBlock
	for i, rule := range rules {
		var kept, gated []string
		for _, resource := range rule.Resources {
			gate, err := isDeprecated(rule.APIGroups, resource)
			if err != nil {
				return nil, fmt.Errorf("%s rules[%d]: %w", sourcePath, i, err)
			}
			if gate {
				gated = append(gated, resource)
			} else {
				kept = append(kept, resource)
			}
		}
		if len(kept) > 0 {
			blocks = append(blocks, ruleBlock{rule: withResources(rule, kept)})
		}
		if len(gated) > 0 {
			blocks = append(blocks, ruleBlock{rule: withResources(rule, gated), deprecated: true})
		}
	}
	return blocks, nil
}

// isDeprecated reports whether resource is gated for every apiGroup of the rule.
// A rule whose groups disagree cannot be split by resource alone, so it is rejected
// rather than silently mis-gated.
func isDeprecated(apiGroups []string, resource string) (bool, error) {
	base := resource
	if idx := strings.Index(resource, "/"); idx >= 0 {
		base = resource[:idx]
	}

	var gated, plain []string
	for _, group := range apiGroups {
		if deprecatedResources[group][base] {
			gated = append(gated, group)
		} else {
			plain = append(plain, group)
		}
	}
	if len(gated) > 0 && len(plain) > 0 {
		return false, fmt.Errorf(
			"resource %q is deprecated for apiGroups %v but not for %v; split the kubebuilder marker so the two do not share a rule",
			resource, gated, plain,
		)
	}
	return len(gated) > 0, nil
}

func withResources(rule rbacv1.PolicyRule, resources []string) rbacv1.PolicyRule {
	out := *rule.DeepCopy()
	out.Resources = resources
	return out
}

// render serialises the blocks, coalescing consecutive gated rules into a single
// conditional so the output stays readable.
func render(blocks []ruleBlock) ([]byte, error) {
	var sb strings.Builder
	sb.WriteString(fileHeader)

	inCondition := false
	for _, block := range blocks {
		if block.deprecated && !inCondition {
			sb.WriteString(conditionStart + "\n")
			inCondition = true
		}
		if !block.deprecated && inCondition {
			sb.WriteString(conditionEnd + "\n")
			inCondition = false
		}
		encoded, err := yaml.Marshal([]rbacv1.PolicyRule{block.rule})
		if err != nil {
			return nil, fmt.Errorf("marshal rule: %w", err)
		}
		sb.Write(encoded)
	}
	if inCondition {
		sb.WriteString(conditionEnd + "\n")
	}
	return []byte(sb.String()), nil
}
