apiVersion: workloads.x-k8s.io/v1alpha1
kind: RoleBasedGroup
metadata:
  name: demo
spec:
  roles:
    - name: engine
      replicas: 3
      rolloutStrategy:
        type: RollingUpdate
        rollingUpdate:
          type: InPlaceIfPossible
      workload:
        apiVersion: workloads.x-k8s.io/v1alpha1
        kind: InstanceSet
      components:
        - name: component-1
          size: 1
          template:
            spec:
              containers:
                - name: main
                  image: nginx:latest
        - name: component-2
          size: 2
          template:
            spec:
              containers:
                - name: main
                  image: nginx:latest
        - name: component-3
          size: 3
          template:
            spec:
              containers:
                - name: main
                  image: nginx:latest