version: "2"
run:
  timeout: 5m
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
        path: internal/*
      - linters:
          - dupl
        path: test/*
      - linters:
          - dupl
        path: cmd/cli/cmd/llm/config/*
      - linters:
          - goconst
        path: _test\.go
      - linters:
          - goconst
        path: test/*
      - linters:
          - staticcheck
        path: _test\.go
        text: ST1001
      - linters:
          - staticcheck
        path: test/*
        text: ST1001
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
