---
extends: default

rules:
  line-length:
    max: 200
  document-start: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation:
    spaces: 2
    indent-sequences: whatever

ignore:
  - config/crd/bases/
  - config/rbac/role.yaml
  - deploy/kubectl/manifests.yaml
  - deploy/helm/rbgs/templates/
