/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	workloadsv1alpha1 "sigs.k8s.io/rbgs/api/workloads/v1alpha1"
)

// AffinitySchedulingStrategyApplyConfiguration represents a declarative configuration of the AffinitySchedulingStrategy type for use
// with apply.
type AffinitySchedulingStrategyApplyConfiguration struct {
	TopologyKey *string                      `json:"topologyKey,omitempty"`
	Ratios      map[string]int32             `json:"ratios,omitempty"`
	BatchMode   *workloadsv1alpha1.BatchMode `json:"batchMode,omitempty"`
}

// AffinitySchedulingStrategyApplyConfiguration constructs a declarative configuration of the AffinitySchedulingStrategy type for use with
// apply.
func AffinitySchedulingStrategy() *AffinitySchedulingStrategyApplyConfiguration {
	return &AffinitySchedulingStrategyApplyConfiguration{}
}

// WithTopologyKey sets the TopologyKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TopologyKey field is set to the value of the last call.
func (b *AffinitySchedulingStrategyApplyConfiguration) WithTopologyKey(value string) *AffinitySchedulingStrategyApplyConfiguration {
	b.TopologyKey = &value
	return b
}

// WithRatios puts the entries into the Ratios field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Ratios field,
// overwriting an existing map entries in Ratios field with the same key.
func (b *AffinitySchedulingStrategyApplyConfiguration) WithRatios(entries map[string]int32) *AffinitySchedulingStrategyApplyConfiguration {
	if b.Ratios == nil && len(entries) > 0 {
		b.Ratios = make(map[string]int32, len(entries))
	}
	for k, v := range entries {
		b.Ratios[k] = v
	}
	return b
}

// WithBatchMode sets the BatchMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BatchMode field is set to the value of the last call.
func (b *AffinitySchedulingStrategyApplyConfiguration) WithBatchMode(value workloadsv1alpha1.BatchMode) *AffinitySchedulingStrategyApplyConfiguration {
	b.BatchMode = &value
	return b
}
