/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CoordinationRollingUpdateApplyConfiguration represents a declarative configuration of the CoordinationRollingUpdate type for use
// with apply.
type CoordinationRollingUpdateApplyConfiguration struct {
	MaxSkew        *string `json:"maxSkew,omitempty"`
	Partition      *string `json:"partition,omitempty"`
	MaxUnavailable *string `json:"maxUnavailable,omitempty"`
}

// CoordinationRollingUpdateApplyConfiguration constructs a declarative configuration of the CoordinationRollingUpdate type for use with
// apply.
func CoordinationRollingUpdate() *CoordinationRollingUpdateApplyConfiguration {
	return &CoordinationRollingUpdateApplyConfiguration{}
}

// WithMaxSkew sets the MaxSkew field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxSkew field is set to the value of the last call.
func (b *CoordinationRollingUpdateApplyConfiguration) WithMaxSkew(value string) *CoordinationRollingUpdateApplyConfiguration {
	b.MaxSkew = &value
	return b
}

// WithPartition sets the Partition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Partition field is set to the value of the last call.
func (b *CoordinationRollingUpdateApplyConfiguration) WithPartition(value string) *CoordinationRollingUpdateApplyConfiguration {
	b.Partition = &value
	return b
}

// WithMaxUnavailable sets the MaxUnavailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxUnavailable field is set to the value of the last call.
func (b *CoordinationRollingUpdateApplyConfiguration) WithMaxUnavailable(value string) *CoordinationRollingUpdateApplyConfiguration {
	b.MaxUnavailable = &value
	return b
}
