/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	workloadsv1alpha1 "sigs.k8s.io/rbgs/api/workloads/v1alpha1"
)

// CoordinationStatusApplyConfiguration represents a declarative configuration of the CoordinationStatus type for use
// with apply.
type CoordinationStatusApplyConfiguration struct {
	Name           *string                                            `json:"name,omitempty"`
	Type           *workloadsv1alpha1.CoordinationType                `json:"type,omitempty"`
	Phase          *workloadsv1alpha1.CoordinationPhase               `json:"phase,omitempty"`
	RoleStates     map[string]RoleCoordinationStateApplyConfiguration `json:"roleStates,omitempty"`
	CurrentBatch   *int32                                             `json:"currentBatch,omitempty"`
	TotalBatches   *int32                                             `json:"totalBatches,omitempty"`
	LastUpdateTime *v1.Time                                           `json:"lastUpdateTime,omitempty"`
	Message        *string                                            `json:"message,omitempty"`
}

// CoordinationStatusApplyConfiguration constructs a declarative configuration of the CoordinationStatus type for use with
// apply.
func CoordinationStatus() *CoordinationStatusApplyConfiguration {
	return &CoordinationStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CoordinationStatusApplyConfiguration) WithName(value string) *CoordinationStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *CoordinationStatusApplyConfiguration) WithType(value workloadsv1alpha1.CoordinationType) *CoordinationStatusApplyConfiguration {
	b.Type = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *CoordinationStatusApplyConfiguration) WithPhase(value workloadsv1alpha1.CoordinationPhase) *CoordinationStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithRoleStates puts the entries into the RoleStates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the RoleStates field,
// overwriting an existing map entries in RoleStates field with the same key.
func (b *CoordinationStatusApplyConfiguration) WithRoleStates(entries map[string]RoleCoordinationStateApplyConfiguration) *CoordinationStatusApplyConfiguration {
	if b.RoleStates == nil && len(entries) > 0 {
		b.RoleStates = make(map[string]RoleCoordinationStateApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.RoleStates[k] = v
	}
	return b
}

// WithCurrentBatch sets the CurrentBatch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentBatch field is set to the value of the last call.
func (b *CoordinationStatusApplyConfiguration) WithCurrentBatch(value int32) *CoordinationStatusApplyConfiguration {
	b.CurrentBatch = &value
	return b
}

// WithTotalBatches sets the TotalBatches field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TotalBatches field is set to the value of the last call.
func (b *CoordinationStatusApplyConfiguration) WithTotalBatches(value int32) *CoordinationStatusApplyConfiguration {
	b.TotalBatches = &value
	return b
}

// WithLastUpdateTime sets the LastUpdateTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdateTime field is set to the value of the last call.
func (b *CoordinationStatusApplyConfiguration) WithLastUpdateTime(value v1.Time) *CoordinationStatusApplyConfiguration {
	b.LastUpdateTime = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *CoordinationStatusApplyConfiguration) WithMessage(value string) *CoordinationStatusApplyConfiguration {
	b.Message = &value
	return b
}
