/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CoordinationStrategyApplyConfiguration represents a declarative configuration of the CoordinationStrategy type for use
// with apply.
type CoordinationStrategyApplyConfiguration struct {
	RollingUpdate *CoordinationRollingUpdateApplyConfiguration `json:"rollingUpdate,omitempty"`
	Scaling       *CoordinationScalingApplyConfiguration       `json:"scaling,omitempty"`
}

// CoordinationStrategyApplyConfiguration constructs a declarative configuration of the CoordinationStrategy type for use with
// apply.
func CoordinationStrategy() *CoordinationStrategyApplyConfiguration {
	return &CoordinationStrategyApplyConfiguration{}
}

// WithRollingUpdate sets the RollingUpdate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RollingUpdate field is set to the value of the last call.
func (b *CoordinationStrategyApplyConfiguration) WithRollingUpdate(value *CoordinationRollingUpdateApplyConfiguration) *CoordinationStrategyApplyConfiguration {
	b.RollingUpdate = value
	return b
}

// WithScaling sets the Scaling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scaling field is set to the value of the last call.
func (b *CoordinationStrategyApplyConfiguration) WithScaling(value *CoordinationScalingApplyConfiguration) *CoordinationStrategyApplyConfiguration {
	b.Scaling = value
	return b
}
