/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// CustomizedActionApplyConfiguration represents a declarative configuration of the CustomizedAction type for use
// with apply.
type CustomizedActionApplyConfiguration struct {
	Containers []v1.Container `json:"containers,omitempty"`
	Volumes    []v1.Volume    `json:"volumes,omitempty"`
}

// CustomizedActionApplyConfiguration constructs a declarative configuration of the CustomizedAction type for use with
// apply.
func CustomizedAction() *CustomizedActionApplyConfiguration {
	return &CustomizedActionApplyConfiguration{}
}

// WithContainers adds the given value to the Containers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Containers field.
func (b *CustomizedActionApplyConfiguration) WithContainers(values ...v1.Container) *CustomizedActionApplyConfiguration {
	for i := range values {
		b.Containers = append(b.Containers, values[i])
	}
	return b
}

// WithVolumes adds the given value to the Volumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Volumes field.
func (b *CustomizedActionApplyConfiguration) WithVolumes(values ...v1.Volume) *CustomizedActionApplyConfiguration {
	for i := range values {
		b.Volumes = append(b.Volumes, values[i])
	}
	return b
}
