/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ImagePreloadActionApplyConfiguration represents a declarative configuration of the ImagePreloadAction type for use
// with apply.
type ImagePreloadActionApplyConfiguration struct {
	Items       []string                  `json:"items,omitempty"`
	PullSecrets []v1.LocalObjectReference `json:"pullSecrets,omitempty"`
}

// ImagePreloadActionApplyConfiguration constructs a declarative configuration of the ImagePreloadAction type for use with
// apply.
func ImagePreloadAction() *ImagePreloadActionApplyConfiguration {
	return &ImagePreloadActionApplyConfiguration{}
}

// WithItems adds the given value to the Items field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Items field.
func (b *ImagePreloadActionApplyConfiguration) WithItems(values ...string) *ImagePreloadActionApplyConfiguration {
	for i := range values {
		b.Items = append(b.Items, values[i])
	}
	return b
}

// WithPullSecrets adds the given value to the PullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PullSecrets field.
func (b *ImagePreloadActionApplyConfiguration) WithPullSecrets(values ...v1.LocalObjectReference) *ImagePreloadActionApplyConfiguration {
	for i := range values {
		b.PullSecrets = append(b.PullSecrets, values[i])
	}
	return b
}
