/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// InstanceSetSpecApplyConfiguration represents a declarative configuration of the InstanceSetSpec type for use
// with apply.
type InstanceSetSpecApplyConfiguration struct {
	Replicas             *int32                                       `json:"replicas,omitempty"`
	Selector             *v1.LabelSelectorApplyConfiguration          `json:"selector,omitempty"`
	InstanceTemplate     *InstanceTemplateApplyConfiguration          `json:"instanceTemplate,omitempty"`
	ScaleStrategy        *InstanceSetScaleStrategyApplyConfiguration  `json:"scaleStrategy,omitempty"`
	UpdateStrategy       *InstanceSetUpdateStrategyApplyConfiguration `json:"updateStrategy,omitempty"`
	RevisionHistoryLimit *int32                                       `json:"revisionHistoryLimit,omitempty"`
	MinReadySeconds      *int32                                       `json:"minReadySeconds,omitempty"`
	Lifecycle            *LifecycleApplyConfiguration                 `json:"lifecycle,omitempty"`
}

// InstanceSetSpecApplyConfiguration constructs a declarative configuration of the InstanceSetSpec type for use with
// apply.
func InstanceSetSpec() *InstanceSetSpecApplyConfiguration {
	return &InstanceSetSpecApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *InstanceSetSpecApplyConfiguration) WithReplicas(value int32) *InstanceSetSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *InstanceSetSpecApplyConfiguration) WithSelector(value *v1.LabelSelectorApplyConfiguration) *InstanceSetSpecApplyConfiguration {
	b.Selector = value
	return b
}

// WithInstanceTemplate sets the InstanceTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceTemplate field is set to the value of the last call.
func (b *InstanceSetSpecApplyConfiguration) WithInstanceTemplate(value *InstanceTemplateApplyConfiguration) *InstanceSetSpecApplyConfiguration {
	b.InstanceTemplate = value
	return b
}

// WithScaleStrategy sets the ScaleStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScaleStrategy field is set to the value of the last call.
func (b *InstanceSetSpecApplyConfiguration) WithScaleStrategy(value *InstanceSetScaleStrategyApplyConfiguration) *InstanceSetSpecApplyConfiguration {
	b.ScaleStrategy = value
	return b
}

// WithUpdateStrategy sets the UpdateStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdateStrategy field is set to the value of the last call.
func (b *InstanceSetSpecApplyConfiguration) WithUpdateStrategy(value *InstanceSetUpdateStrategyApplyConfiguration) *InstanceSetSpecApplyConfiguration {
	b.UpdateStrategy = value
	return b
}

// WithRevisionHistoryLimit sets the RevisionHistoryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RevisionHistoryLimit field is set to the value of the last call.
func (b *InstanceSetSpecApplyConfiguration) WithRevisionHistoryLimit(value int32) *InstanceSetSpecApplyConfiguration {
	b.RevisionHistoryLimit = &value
	return b
}

// WithMinReadySeconds sets the MinReadySeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinReadySeconds field is set to the value of the last call.
func (b *InstanceSetSpecApplyConfiguration) WithMinReadySeconds(value int32) *InstanceSetSpecApplyConfiguration {
	b.MinReadySeconds = &value
	return b
}

// WithLifecycle sets the Lifecycle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Lifecycle field is set to the value of the last call.
func (b *InstanceSetSpecApplyConfiguration) WithLifecycle(value *LifecycleApplyConfiguration) *InstanceSetSpecApplyConfiguration {
	b.Lifecycle = value
	return b
}
