/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// InstanceComponentApplyConfiguration represents a declarative configuration of the InstanceComponent type for use
// with apply.
type InstanceComponentApplyConfiguration struct {
	Name        *string                               `json:"name,omitempty"`
	Size        *int32                                `json:"size,omitempty"`
	ServiceName *string                               `json:"serviceName,omitempty"`
	Template    *v1.PodTemplateSpecApplyConfiguration `json:"template,omitempty"`
}

// InstanceComponentApplyConfiguration constructs a declarative configuration of the InstanceComponent type for use with
// apply.
func InstanceComponent() *InstanceComponentApplyConfiguration {
	return &InstanceComponentApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *InstanceComponentApplyConfiguration) WithName(value string) *InstanceComponentApplyConfiguration {
	b.Name = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *InstanceComponentApplyConfiguration) WithSize(value int32) *InstanceComponentApplyConfiguration {
	b.Size = &value
	return b
}

// WithServiceName sets the ServiceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceName field is set to the value of the last call.
func (b *InstanceComponentApplyConfiguration) WithServiceName(value string) *InstanceComponentApplyConfiguration {
	b.ServiceName = &value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *InstanceComponentApplyConfiguration) WithTemplate(value *v1.PodTemplateSpecApplyConfiguration) *InstanceComponentApplyConfiguration {
	b.Template = value
	return b
}
