/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// InstanceSetStatusApplyConfiguration represents a declarative configuration of the InstanceSetStatus type for use
// with apply.
type InstanceSetStatusApplyConfiguration struct {
	ObservedGeneration      *int64                                   `json:"observedGeneration,omitempty"`
	Replicas                *int32                                   `json:"replicas,omitempty"`
	ReadyReplicas           *int32                                   `json:"readyReplicas,omitempty"`
	AvailableReplicas       *int32                                   `json:"availableReplicas,omitempty"`
	CurrentReplicas         *int32                                   `json:"currentReplicas,omitempty"`
	UpdatedReplicas         *int32                                   `json:"updatedReplicas,omitempty"`
	UpdatedReadyReplicas    *int32                                   `json:"updatedReadyReplicas,omitempty"`
	ExpectedUpdatedReplicas *int32                                   `json:"expectedUpdatedReplicas,omitempty"`
	UpdateRevision          *string                                  `json:"updateRevision,omitempty"`
	CurrentRevision         *string                                  `json:"currentRevision,omitempty"`
	CollisionCount          *int32                                   `json:"collisionCount,omitempty"`
	Conditions              []InstanceSetConditionApplyConfiguration `json:"conditions,omitempty"`
	LabelSelector           *string                                  `json:"labelSelector,omitempty"`
}

// InstanceSetStatusApplyConfiguration constructs a declarative configuration of the InstanceSetStatus type for use with
// apply.
func InstanceSetStatus() *InstanceSetStatusApplyConfiguration {
	return &InstanceSetStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *InstanceSetStatusApplyConfiguration) WithObservedGeneration(value int64) *InstanceSetStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *InstanceSetStatusApplyConfiguration) WithReplicas(value int32) *InstanceSetStatusApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *InstanceSetStatusApplyConfiguration) WithReadyReplicas(value int32) *InstanceSetStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithAvailableReplicas sets the AvailableReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableReplicas field is set to the value of the last call.
func (b *InstanceSetStatusApplyConfiguration) WithAvailableReplicas(value int32) *InstanceSetStatusApplyConfiguration {
	b.AvailableReplicas = &value
	return b
}

// WithCurrentReplicas sets the CurrentReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentReplicas field is set to the value of the last call.
func (b *InstanceSetStatusApplyConfiguration) WithCurrentReplicas(value int32) *InstanceSetStatusApplyConfiguration {
	b.CurrentReplicas = &value
	return b
}

// WithUpdatedReplicas sets the UpdatedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedReplicas field is set to the value of the last call.
func (b *InstanceSetStatusApplyConfiguration) WithUpdatedReplicas(value int32) *InstanceSetStatusApplyConfiguration {
	b.UpdatedReplicas = &value
	return b
}

// WithUpdatedReadyReplicas sets the UpdatedReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedReadyReplicas field is set to the value of the last call.
func (b *InstanceSetStatusApplyConfiguration) WithUpdatedReadyReplicas(value int32) *InstanceSetStatusApplyConfiguration {
	b.UpdatedReadyReplicas = &value
	return b
}

// WithExpectedUpdatedReplicas sets the ExpectedUpdatedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpectedUpdatedReplicas field is set to the value of the last call.
func (b *InstanceSetStatusApplyConfiguration) WithExpectedUpdatedReplicas(value int32) *InstanceSetStatusApplyConfiguration {
	b.ExpectedUpdatedReplicas = &value
	return b
}

// WithUpdateRevision sets the UpdateRevision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdateRevision field is set to the value of the last call.
func (b *InstanceSetStatusApplyConfiguration) WithUpdateRevision(value string) *InstanceSetStatusApplyConfiguration {
	b.UpdateRevision = &value
	return b
}

// WithCurrentRevision sets the CurrentRevision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentRevision field is set to the value of the last call.
func (b *InstanceSetStatusApplyConfiguration) WithCurrentRevision(value string) *InstanceSetStatusApplyConfiguration {
	b.CurrentRevision = &value
	return b
}

// WithCollisionCount sets the CollisionCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollisionCount field is set to the value of the last call.
func (b *InstanceSetStatusApplyConfiguration) WithCollisionCount(value int32) *InstanceSetStatusApplyConfiguration {
	b.CollisionCount = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *InstanceSetStatusApplyConfiguration) WithConditions(values ...*InstanceSetConditionApplyConfiguration) *InstanceSetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithLabelSelector sets the LabelSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelSelector field is set to the value of the last call.
func (b *InstanceSetStatusApplyConfiguration) WithLabelSelector(value string) *InstanceSetStatusApplyConfiguration {
	b.LabelSelector = &value
	return b
}
