/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LifecycleHookApplyConfiguration represents a declarative configuration of the LifecycleHook type for use
// with apply.
type LifecycleHookApplyConfiguration struct {
	LabelsHandler     map[string]string `json:"labelsHandler,omitempty"`
	FinalizersHandler []string          `json:"finalizersHandler,omitempty"`
	MarkNotReady      *bool             `json:"markPodNotReady,omitempty"`
}

// LifecycleHookApplyConfiguration constructs a declarative configuration of the LifecycleHook type for use with
// apply.
func LifecycleHook() *LifecycleHookApplyConfiguration {
	return &LifecycleHookApplyConfiguration{}
}

// WithLabelsHandler puts the entries into the LabelsHandler field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the LabelsHandler field,
// overwriting an existing map entries in LabelsHandler field with the same key.
func (b *LifecycleHookApplyConfiguration) WithLabelsHandler(entries map[string]string) *LifecycleHookApplyConfiguration {
	if b.LabelsHandler == nil && len(entries) > 0 {
		b.LabelsHandler = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.LabelsHandler[k] = v
	}
	return b
}

// WithFinalizersHandler adds the given value to the FinalizersHandler field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the FinalizersHandler field.
func (b *LifecycleHookApplyConfiguration) WithFinalizersHandler(values ...string) *LifecycleHookApplyConfiguration {
	for i := range values {
		b.FinalizersHandler = append(b.FinalizersHandler, values[i])
	}
	return b
}

// WithMarkNotReady sets the MarkNotReady field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MarkNotReady field is set to the value of the last call.
func (b *LifecycleHookApplyConfiguration) WithMarkNotReady(value bool) *LifecycleHookApplyConfiguration {
	b.MarkNotReady = &value
	return b
}
