/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RoleBasedGroupWarmUpSpecApplyConfiguration represents a declarative configuration of the RoleBasedGroupWarmUpSpec type for use
// with apply.
type RoleBasedGroupWarmUpSpecApplyConfiguration struct {
	TargetNodes          *TargetNodesApplyConfiguration          `json:"targetNodes,omitempty"`
	TargetRoleBasedGroup *TargetRoleBasedGroupApplyConfiguration `json:"targetRoleBasedGroup,omitempty"`
}

// RoleBasedGroupWarmUpSpecApplyConfiguration constructs a declarative configuration of the RoleBasedGroupWarmUpSpec type for use with
// apply.
func RoleBasedGroupWarmUpSpec() *RoleBasedGroupWarmUpSpecApplyConfiguration {
	return &RoleBasedGroupWarmUpSpecApplyConfiguration{}
}

// WithTargetNodes sets the TargetNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetNodes field is set to the value of the last call.
func (b *RoleBasedGroupWarmUpSpecApplyConfiguration) WithTargetNodes(value *TargetNodesApplyConfiguration) *RoleBasedGroupWarmUpSpecApplyConfiguration {
	b.TargetNodes = value
	return b
}

// WithTargetRoleBasedGroup sets the TargetRoleBasedGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetRoleBasedGroup field is set to the value of the last call.
func (b *RoleBasedGroupWarmUpSpecApplyConfiguration) WithTargetRoleBasedGroup(value *TargetRoleBasedGroupApplyConfiguration) *RoleBasedGroupWarmUpSpecApplyConfiguration {
	b.TargetRoleBasedGroup = value
	return b
}
