/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RoleCoordinationStateApplyConfiguration represents a declarative configuration of the RoleCoordinationState type for use
// with apply.
type RoleCoordinationStateApplyConfiguration struct {
	ReadyReplicas   *int32 `json:"readyReplicas,omitempty"`
	TargetReplicas  *int32 `json:"targetReplicas,omitempty"`
	UpdatedReplicas *int32 `json:"updatedReplicas,omitempty"`
}

// RoleCoordinationStateApplyConfiguration constructs a declarative configuration of the RoleCoordinationState type for use with
// apply.
func RoleCoordinationState() *RoleCoordinationStateApplyConfiguration {
	return &RoleCoordinationStateApplyConfiguration{}
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *RoleCoordinationStateApplyConfiguration) WithReadyReplicas(value int32) *RoleCoordinationStateApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithTargetReplicas sets the TargetReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetReplicas field is set to the value of the last call.
func (b *RoleCoordinationStateApplyConfiguration) WithTargetReplicas(value int32) *RoleCoordinationStateApplyConfiguration {
	b.TargetReplicas = &value
	return b
}

// WithUpdatedReplicas sets the UpdatedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedReplicas field is set to the value of the last call.
func (b *RoleCoordinationStateApplyConfiguration) WithUpdatedReplicas(value int32) *RoleCoordinationStateApplyConfiguration {
	b.UpdatedReplicas = &value
	return b
}
