/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	workloadsv1alpha1 "sigs.k8s.io/rbgs/api/workloads/v1alpha1"
)

// SegmentSchedulingApplyConfiguration represents a declarative configuration of the SegmentScheduling type for use
// with apply.
type SegmentSchedulingApplyConfiguration struct {
	SegmentSize       map[string]int32                                `json:"segment,omitempty"`
	PartitionStrategy *workloadsv1alpha1.SegmentPartitionStrategyType `json:"partitionStrategy,omitempty"`
}

// SegmentSchedulingApplyConfiguration constructs a declarative configuration of the SegmentScheduling type for use with
// apply.
func SegmentScheduling() *SegmentSchedulingApplyConfiguration {
	return &SegmentSchedulingApplyConfiguration{}
}

// WithSegmentSize puts the entries into the SegmentSize field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the SegmentSize field,
// overwriting an existing map entries in SegmentSize field with the same key.
func (b *SegmentSchedulingApplyConfiguration) WithSegmentSize(entries map[string]int32) *SegmentSchedulingApplyConfiguration {
	if b.SegmentSize == nil && len(entries) > 0 {
		b.SegmentSize = make(map[string]int32, len(entries))
	}
	for k, v := range entries {
		b.SegmentSize[k] = v
	}
	return b
}

// WithPartitionStrategy sets the PartitionStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PartitionStrategy field is set to the value of the last call.
func (b *SegmentSchedulingApplyConfiguration) WithPartitionStrategy(value workloadsv1alpha1.SegmentPartitionStrategyType) *SegmentSchedulingApplyConfiguration {
	b.PartitionStrategy = &value
	return b
}
