/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TargetRoleBasedGroupApplyConfiguration represents a declarative configuration of the TargetRoleBasedGroup type for use
// with apply.
type TargetRoleBasedGroupApplyConfiguration struct {
	Name  *string                                    `json:"name,omitempty"`
	Roles map[string]WarmUpActionsApplyConfiguration `json:"roles,omitempty"`
}

// TargetRoleBasedGroupApplyConfiguration constructs a declarative configuration of the TargetRoleBasedGroup type for use with
// apply.
func TargetRoleBasedGroup() *TargetRoleBasedGroupApplyConfiguration {
	return &TargetRoleBasedGroupApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TargetRoleBasedGroupApplyConfiguration) WithName(value string) *TargetRoleBasedGroupApplyConfiguration {
	b.Name = &value
	return b
}

// WithRoles puts the entries into the Roles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Roles field,
// overwriting an existing map entries in Roles field with the same key.
func (b *TargetRoleBasedGroupApplyConfiguration) WithRoles(entries map[string]WarmUpActionsApplyConfiguration) *TargetRoleBasedGroupApplyConfiguration {
	if b.Roles == nil && len(entries) > 0 {
		b.Roles = make(map[string]WarmUpActionsApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.Roles[k] = v
	}
	return b
}
