/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TargetNodesApplyConfiguration represents a declarative configuration of the TargetNodes type for use
// with apply.
type TargetNodesApplyConfiguration struct {
	NodeNames                       []string          `json:"nodeNames,omitempty"`
	NodeSelector                    map[string]string `json:"nodeSelector,omitempty"`
	WarmUpActionsApplyConfiguration `json:",inline"`
}

// TargetNodesApplyConfiguration constructs a declarative configuration of the TargetNodes type for use with
// apply.
func TargetNodes() *TargetNodesApplyConfiguration {
	return &TargetNodesApplyConfiguration{}
}

// WithNodeNames adds the given value to the NodeNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NodeNames field.
func (b *TargetNodesApplyConfiguration) WithNodeNames(values ...string) *TargetNodesApplyConfiguration {
	for i := range values {
		b.NodeNames = append(b.NodeNames, values[i])
	}
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *TargetNodesApplyConfiguration) WithNodeSelector(entries map[string]string) *TargetNodesApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithImagePreload sets the ImagePreload field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagePreload field is set to the value of the last call.
func (b *TargetNodesApplyConfiguration) WithImagePreload(value *ImagePreloadActionApplyConfiguration) *TargetNodesApplyConfiguration {
	b.WarmUpActionsApplyConfiguration.ImagePreload = value
	return b
}

// WithCustomizedAction sets the CustomizedAction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomizedAction field is set to the value of the last call.
func (b *TargetNodesApplyConfiguration) WithCustomizedAction(value *CustomizedActionApplyConfiguration) *TargetNodesApplyConfiguration {
	b.WarmUpActionsApplyConfiguration.CustomizedAction = value
	return b
}
