/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// WarmUpActionsApplyConfiguration represents a declarative configuration of the WarmUpActions type for use
// with apply.
type WarmUpActionsApplyConfiguration struct {
	ImagePreload     *ImagePreloadActionApplyConfiguration `json:"imagePreload,omitempty"`
	CustomizedAction *CustomizedActionApplyConfiguration   `json:"customizedAction,omitempty"`
}

// WarmUpActionsApplyConfiguration constructs a declarative configuration of the WarmUpActions type for use with
// apply.
func WarmUpActions() *WarmUpActionsApplyConfiguration {
	return &WarmUpActionsApplyConfiguration{}
}

// WithImagePreload sets the ImagePreload field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagePreload field is set to the value of the last call.
func (b *WarmUpActionsApplyConfiguration) WithImagePreload(value *ImagePreloadActionApplyConfiguration) *WarmUpActionsApplyConfiguration {
	b.ImagePreload = value
	return b
}

// WithCustomizedAction sets the CustomizedAction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomizedAction field is set to the value of the last call.
func (b *WarmUpActionsApplyConfiguration) WithCustomizedAction(value *CustomizedActionApplyConfiguration) *WarmUpActionsApplyConfiguration {
	b.CustomizedAction = value
	return b
}
