apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
  labels:
    control-plane: rbgs-controller
    app.kubernetes.io/name: rbgs
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: webhook
  selector:
    control-plane: rbgs-controller
