---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller-secret-role
  namespace: system
  labels:
    app.kubernetes.io/name: rbgs
    app.kubernetes.io/managed-by: kustomize
rules:
# Allow creating the webhook cert secret if it does not yet exist.
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
# Allow reading and updating only the specific webhook cert secret.
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - rbgs-webhook-cert
  verbs:
  - get
  - update
