/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	workloadsv1alpha2 "sigs.k8s.io/rbgs/api/workloads/v1alpha2"
)

// CoordinatedPolicyLister helps list CoordinatedPolicies.
// All objects returned here must be treated as read-only.
type CoordinatedPolicyLister interface {
	// List lists all CoordinatedPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha2.CoordinatedPolicy, err error)
	// CoordinatedPolicies returns an object that can list and get CoordinatedPolicies.
	CoordinatedPolicies(namespace string) CoordinatedPolicyNamespaceLister
	CoordinatedPolicyListerExpansion
}

// coordinatedPolicyLister implements the CoordinatedPolicyLister interface.
type coordinatedPolicyLister struct {
	listers.ResourceIndexer[*workloadsv1alpha2.CoordinatedPolicy]
}

// NewCoordinatedPolicyLister returns a new CoordinatedPolicyLister.
func NewCoordinatedPolicyLister(indexer cache.Indexer) CoordinatedPolicyLister {
	return &coordinatedPolicyLister{listers.New[*workloadsv1alpha2.CoordinatedPolicy](indexer, workloadsv1alpha2.Resource("coordinatedpolicy"))}
}

// CoordinatedPolicies returns an object that can list and get CoordinatedPolicies.
func (s *coordinatedPolicyLister) CoordinatedPolicies(namespace string) CoordinatedPolicyNamespaceLister {
	return coordinatedPolicyNamespaceLister{listers.NewNamespaced[*workloadsv1alpha2.CoordinatedPolicy](s.ResourceIndexer, namespace)}
}

// CoordinatedPolicyNamespaceLister helps list and get CoordinatedPolicies.
// All objects returned here must be treated as read-only.
type CoordinatedPolicyNamespaceLister interface {
	// List lists all CoordinatedPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha2.CoordinatedPolicy, err error)
	// Get retrieves the CoordinatedPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*workloadsv1alpha2.CoordinatedPolicy, error)
	CoordinatedPolicyNamespaceListerExpansion
}

// coordinatedPolicyNamespaceLister implements the CoordinatedPolicyNamespaceLister
// interface.
type coordinatedPolicyNamespaceLister struct {
	listers.ResourceIndexer[*workloadsv1alpha2.CoordinatedPolicy]
}
