/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

// CoordinatedPolicyListerExpansion allows custom methods to be added to
// CoordinatedPolicyLister.
type CoordinatedPolicyListerExpansion interface{}

// CoordinatedPolicyNamespaceListerExpansion allows custom methods to be added to
// CoordinatedPolicyNamespaceLister.
type CoordinatedPolicyNamespaceListerExpansion interface{}

// RoleBasedGroupListerExpansion allows custom methods to be added to
// RoleBasedGroupLister.
type RoleBasedGroupListerExpansion interface{}

// RoleBasedGroupNamespaceListerExpansion allows custom methods to be added to
// RoleBasedGroupNamespaceLister.
type RoleBasedGroupNamespaceListerExpansion interface{}

// RoleBasedGroupSetListerExpansion allows custom methods to be added to
// RoleBasedGroupSetLister.
type RoleBasedGroupSetListerExpansion interface{}

// RoleBasedGroupSetNamespaceListerExpansion allows custom methods to be added to
// RoleBasedGroupSetNamespaceLister.
type RoleBasedGroupSetNamespaceListerExpansion interface{}

// RoleInstanceListerExpansion allows custom methods to be added to
// RoleInstanceLister.
type RoleInstanceListerExpansion interface{}

// RoleInstanceNamespaceListerExpansion allows custom methods to be added to
// RoleInstanceNamespaceLister.
type RoleInstanceNamespaceListerExpansion interface{}

// RoleInstanceSetListerExpansion allows custom methods to be added to
// RoleInstanceSetLister.
type RoleInstanceSetListerExpansion interface{}

// RoleInstanceSetNamespaceListerExpansion allows custom methods to be added to
// RoleInstanceSetNamespaceLister.
type RoleInstanceSetNamespaceListerExpansion interface{}
