/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	workloadsv1alpha2 "sigs.k8s.io/rbgs/api/workloads/v1alpha2"
)

// RoleInstanceLister helps list RoleInstances.
// All objects returned here must be treated as read-only.
type RoleInstanceLister interface {
	// List lists all RoleInstances in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha2.RoleInstance, err error)
	// RoleInstances returns an object that can list and get RoleInstances.
	RoleInstances(namespace string) RoleInstanceNamespaceLister
	RoleInstanceListerExpansion
}

// roleInstanceLister implements the RoleInstanceLister interface.
type roleInstanceLister struct {
	listers.ResourceIndexer[*workloadsv1alpha2.RoleInstance]
}

// NewRoleInstanceLister returns a new RoleInstanceLister.
func NewRoleInstanceLister(indexer cache.Indexer) RoleInstanceLister {
	return &roleInstanceLister{listers.New[*workloadsv1alpha2.RoleInstance](indexer, workloadsv1alpha2.Resource("roleinstance"))}
}

// RoleInstances returns an object that can list and get RoleInstances.
func (s *roleInstanceLister) RoleInstances(namespace string) RoleInstanceNamespaceLister {
	return roleInstanceNamespaceLister{listers.NewNamespaced[*workloadsv1alpha2.RoleInstance](s.ResourceIndexer, namespace)}
}

// RoleInstanceNamespaceLister helps list and get RoleInstances.
// All objects returned here must be treated as read-only.
type RoleInstanceNamespaceLister interface {
	// List lists all RoleInstances in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha2.RoleInstance, err error)
	// Get retrieves the RoleInstance from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*workloadsv1alpha2.RoleInstance, error)
	RoleInstanceNamespaceListerExpansion
}

// roleInstanceNamespaceLister implements the RoleInstanceNamespaceLister
// interface.
type roleInstanceNamespaceLister struct {
	listers.ResourceIndexer[*workloadsv1alpha2.RoleInstance]
}
