/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	workloadsv1alpha2 "sigs.k8s.io/rbgs/api/workloads/v1alpha2"
)

// RoleInstanceSetLister helps list RoleInstanceSets.
// All objects returned here must be treated as read-only.
type RoleInstanceSetLister interface {
	// List lists all RoleInstanceSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha2.RoleInstanceSet, err error)
	// RoleInstanceSets returns an object that can list and get RoleInstanceSets.
	RoleInstanceSets(namespace string) RoleInstanceSetNamespaceLister
	RoleInstanceSetListerExpansion
}

// roleInstanceSetLister implements the RoleInstanceSetLister interface.
type roleInstanceSetLister struct {
	listers.ResourceIndexer[*workloadsv1alpha2.RoleInstanceSet]
}

// NewRoleInstanceSetLister returns a new RoleInstanceSetLister.
func NewRoleInstanceSetLister(indexer cache.Indexer) RoleInstanceSetLister {
	return &roleInstanceSetLister{listers.New[*workloadsv1alpha2.RoleInstanceSet](indexer, workloadsv1alpha2.Resource("roleinstanceset"))}
}

// RoleInstanceSets returns an object that can list and get RoleInstanceSets.
func (s *roleInstanceSetLister) RoleInstanceSets(namespace string) RoleInstanceSetNamespaceLister {
	return roleInstanceSetNamespaceLister{listers.NewNamespaced[*workloadsv1alpha2.RoleInstanceSet](s.ResourceIndexer, namespace)}
}

// RoleInstanceSetNamespaceLister helps list and get RoleInstanceSets.
// All objects returned here must be treated as read-only.
type RoleInstanceSetNamespaceLister interface {
	// List lists all RoleInstanceSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha2.RoleInstanceSet, err error)
	// Get retrieves the RoleInstanceSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*workloadsv1alpha2.RoleInstanceSet, error)
	RoleInstanceSetNamespaceListerExpansion
}

// roleInstanceSetNamespaceLister implements the RoleInstanceSetNamespaceLister
// interface.
type roleInstanceSetNamespaceLister struct {
	listers.ResourceIndexer[*workloadsv1alpha2.RoleInstanceSet]
}
