/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"go.yaml.in/yaml/v2"
	"k8s.io/klog/v2"
)

// LocateOutputDirectory finds the latest output directory generated by aiconfigurator
func LocateOutputDirectory(config *TaskConfig) (string, error) {
	// Determine if model name is a Hugging Face ID or a local path
	// HF IDs are like "Qwen/Qwen3-32B" (org/model), local paths start with /, ./, ../, or have drive letters
	modelName := config.ModelName
	searchDir := config.SaveDir
	var modelBaseName string

	if isHuggingFaceID(modelName) {
		// For HF IDs, aiconfigurator creates hierarchical directories:
		// {save-dir}/{org}/{model}_{system}_{backend}_isl{isl}_osl{osl}_ttft{ttft}_tpot{tpot}_{timestamp}
		parts := strings.Split(modelName, "/")
		modelBaseName = parts[len(parts)-1]
		if len(parts) > 1 {
			// Append parent directories (org name) to save-dir
			searchDir = filepath.Join(append([]string{searchDir}, parts[:len(parts)-1]...)...)
		}
	} else {
		// For local paths, use basename only
		// aiconfigurator outputs directly under save-dir
		modelBaseName = GetModelBaseName(modelName)
	}

	// Build the directory prefix pattern
	// Format: {model_base_name}_{system}_{backend}_isl{isl}_osl{osl}_ttft{ttft}_tpot{tpot}_
	prefix := fmt.Sprintf("%s_%s_%s_isl%d_osl%d_ttft%d_tpot%d_",
		modelBaseName,
		config.SystemName,
		config.BackendName,
		config.ISL,
		config.OSL,
		int(config.TTFT),
		int(config.TPOT),
	)

	klog.V(2).Infof("Looking in directory: %s", searchDir)
	klog.V(2).Infof("Looking for directories with prefix: %s*", prefix)

	// Read search directory
	entries, err := os.ReadDir(searchDir)
	if err != nil {
		return "", fmt.Errorf("failed to read search directory %s: %w", searchDir, err)
	}

	// Find matching directories
	var matchingDirs []string
	for _, entry := range entries {
		if entry.IsDir() && strings.HasPrefix(entry.Name(), prefix) {
			fullPath := filepath.Join(searchDir, entry.Name())
			matchingDirs = append(matchingDirs, fullPath)
		}
	}

	if len(matchingDirs) == 0 {
		return "", fmt.Errorf("no output directory found in %s matching pattern: %s*\nPlease check if aiconfigurator executed successfully", searchDir, prefix)
	}

	if len(matchingDirs) > 1 {
		// Sort by modification time (most recent first)
		sort.Slice(matchingDirs, func(i, j int) bool {
			infoI, errI := os.Stat(matchingDirs[i])
			infoJ, errJ := os.Stat(matchingDirs[j])
			if errI != nil || errJ != nil {
				klog.Fatalf("failed to get directory info: %v, %v", errI, errJ)
			}
			return infoI.ModTime().After(infoJ.ModTime())
		})
	}

	latestDir := matchingDirs[0]
	klog.V(2).Infof("Found latest output directory: %s", latestDir)

	// Verify directory structure
	aggDir := filepath.Join(latestDir, "agg")
	disaggDir := filepath.Join(latestDir, "disagg")

	if !dirExists(aggDir) || !dirExists(disaggDir) {
		return "", fmt.Errorf("output directory %s is missing required subdirectories (agg/disagg)", latestDir)
	}

	return latestDir, nil
}

// ParseGeneratorConfigs parses both agg and disagg generator configurations
func ParseGeneratorConfigs(outputDir string) (aggConfig, disaggConfig *GeneratorConfig, err error) {
	// Parse aggregation mode config
	aggConfigPath := filepath.Join(outputDir, "agg", "top1", "generator_config.yaml")
	aggConfig, err = parseGeneratorConfig(aggConfigPath)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to parse aggregation config: %w", err)
	}

	// Parse disaggregation mode config
	disaggConfigPath := filepath.Join(outputDir, "disagg", "top1", "generator_config.yaml")
	disaggConfig, err = parseGeneratorConfig(disaggConfigPath)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to parse disaggregation config: %w", err)
	}

	return aggConfig, disaggConfig, nil
}

// parseGeneratorConfig reads and parses a generator_config.yaml file
func parseGeneratorConfig(configPath string) (*GeneratorConfig, error) {
	klog.V(2).Infof("Parsing generator config from: %s", configPath)

	data, err := os.ReadFile(configPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read config file %s: %w", configPath, err)
	}

	var config GeneratorConfig
	if err := yaml.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("failed to unmarshal YAML from %s: %w", configPath, err)
	}

	// Validate required fields
	if config.DynConfig.Mode == "" {
		return nil, fmt.Errorf("config missing required field: DynConfig.mode")
	}

	klog.V(2).Infof("Successfully parsed %s mode config", config.DynConfig.Mode)
	return &config, nil
}

// dirExists checks if a directory exists
func dirExists(path string) bool {
	info, err := os.Stat(path)
	if err != nil {
		return false
	}
	return info.IsDir()
}

// isHuggingFaceID determines if the model name is a Hugging Face model ID
// rather than a local filesystem path.
// HF IDs: "Qwen/Qwen3-32B", "bert-base-uncased", "org/model-name"
// Local paths: "/models/foo", "./models/foo", "C:\models\foo"
func isHuggingFaceID(modelName string) bool {
	// Empty string is not a valid HF ID
	if modelName == "" {
		return false
	}

	// Check for local path indicators
	// Unix absolute path
	if strings.HasPrefix(modelName, "/") {
		return false
	}
	// Relative path
	if strings.HasPrefix(modelName, "./") || strings.HasPrefix(modelName, "../") {
		return false
	}
	// Windows drive letter (e.g., "C:", "D:")
	if len(modelName) >= 2 && modelName[1] == ':' && (modelName[0] >= 'A' && modelName[0] <= 'Z' || modelName[0] >= 'a' && modelName[0] <= 'z') {
		return false
	}
	// Windows path separator
	if strings.Contains(modelName, "\\") {
		return false
	}

	// If it passes all checks, treat it as a Hugging Face ID
	return true
}
