/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package generate

// Configurator tool constants
const (
	AIConfigurator = "aiconfigurator"
)

// Backend constants
const (
	BackendSGLang = "sglang"
	BackendVLLM   = "vllm"
	BackendTRTLLM = "trtllm"
)

// Database mode constants
const (
	DatabaseModeSilicon   = "SILICON"
	DatabaseModeHybrid    = "HYBRID"
	DatabaseModeEmpirical = "EMPIRICAL"
	DatabaseModeSOL       = "SOL"
)

// Deployment mode constants
const (
	DeploymentModeDisagg = "disagg"
	DeploymentModeAgg    = "agg"
)

// TaskConfig holds the configuration for model deployment recommendation
type TaskConfig struct {
	ServingMode      string
	ModelName        string
	HuggingFaceID    string
	SystemName       string
	DecodeSystemName string
	BackendName      string
	BackendVersion   string
	QuantMode        string
	ISL              int
	OSL              int
	Prefix           int
	TTFT             float64
	TPOT             float64
	RequestLatency   float64
	EnableWideep     bool
	TotalGPUs        int
	Profiles         []string
	YAMLConfig       map[string]interface{}
	DatabaseMode     string
	SaveDir          string
	Debug            bool
	ConfiguratorTool string            // Name of the configurator tool to use (default: aiconfigurator)
	ExtraArgs        map[string]string // Additional unrecognized arguments
}

// GeneratorConfig represents the configuration generated by aiconfigurator
type GeneratorConfig struct {
	K8s     K8sConfig     `yaml:"k8s"`
	Workers WorkersConfig `yaml:"workers"`
	Params  ParamsConfig  `yaml:"params"`
}

// K8sConfig holds Kubernetes-related configuration
type K8sConfig struct {
	NamePrefix         string `yaml:"name_prefix"`
	K8sNamespace       string `yaml:"k8s_namespace"`
	K8sImage           string `yaml:"k8s_image"`
	K8sImagePullSecret string `yaml:"k8s_image_pull_secret"`
	K8sEngineMode      string `yaml:"k8s_engine_mode"`
	K8sModelCache      string `yaml:"k8s_model_cache"`
	Mode               string `yaml:"mode"`
	RouterMode         string `yaml:"router_mode"`
	IsKV               bool   `yaml:"is_kv"`
	EnableRouter       bool   `yaml:"enable_router"`
	Name               string `yaml:"name"`
	UseEngineCM        bool   `yaml:"use_engine_cm"`
	PrefillEngineArgs  string `yaml:"prefill_engine_args"`
	DecodeEngineArgs   string `yaml:"decode_engine_args"`
	AggEngineArgs      string `yaml:"agg_engine_args"`
}

// WorkersConfig holds the number of workers for each role
type WorkersConfig struct {
	PrefillWorkers       int `yaml:"prefill_workers"`
	DecodeWorkers        int `yaml:"decode_workers"`
	AggWorkers           int `yaml:"agg_workers"`
	PrefillGPUsPerWorker int `yaml:"prefill_gpus_per_worker"`
	DecodeGPUsPerWorker  int `yaml:"decode_gpus_per_worker"`
	AggGPUsPerWorker     int `yaml:"agg_gpus_per_worker"`
}

// ParamsConfig holds the parameters for different worker types
type ParamsConfig struct {
	Prefill map[string]interface{} `yaml:"prefill"`
	Decode  map[string]interface{} `yaml:"decode"`
	Agg     map[string]interface{} `yaml:"agg"`
}

// WorkerParams represents the parameters for a single worker type
type WorkerParams struct {
	TensorParallelSize    int `yaml:"tensor_parallel_size"`
	PipelineParallelSize  int `yaml:"pipeline_parallel_size"`
	DataParallelSize      int `yaml:"data_parallel_size"`
	MoETensorParallelSize int `yaml:"moe_tensor_parallel_size"`
	MoEExpertParallelSize int `yaml:"moe_expert_parallel_size"`
}

// DeploymentPlan represents a complete deployment plan
type DeploymentPlan struct {
	Mode          string // "disagg" or "agg"
	Config        *GeneratorConfig
	OutputPath    string
	ModelName     string
	BackendName   string
	HuggingFaceID string
}

// getIntFromMap safely retrieves an int value from a map
func getIntFromMap(m map[string]interface{}, key string) int {
	if v, ok := m[key]; ok {
		switch val := v.(type) {
		case int:
			return val
		case float64:
			return int(val)
		}
	}
	return 0
}

// GetWorkerParams extracts WorkerParams from a params map
func GetWorkerParams(params map[string]interface{}) WorkerParams {
	return WorkerParams{
		TensorParallelSize:    getIntFromMap(params, "tensor_parallel_size"),
		PipelineParallelSize:  getIntFromMap(params, "pipeline_parallel_size"),
		DataParallelSize:      getIntFromMap(params, "data_parallel_size"),
		MoETensorParallelSize: getIntFromMap(params, "moe_tensor_parallel_size"),
		MoEExpertParallelSize: getIntFromMap(params, "moe_expert_parallel_size"),
	}
}
