apiVersion: v1
kind: Service
metadata:
  name: rbgs-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: rbgs-controller
spec:
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: webhook
  selector:
    control-plane: rbgs-controller
