/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apiworkloadsv1alpha1 "sigs.k8s.io/rbgs/api/workloads/v1alpha1"
	versioned "sigs.k8s.io/rbgs/client-go/clientset/versioned"
	internalinterfaces "sigs.k8s.io/rbgs/client-go/informers/externalversions/internalinterfaces"
	workloadsv1alpha1 "sigs.k8s.io/rbgs/client-go/listers/workloads/v1alpha1"
)

// InstanceSetInformer provides access to a shared informer and lister for
// InstanceSets.
type InstanceSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() workloadsv1alpha1.InstanceSetLister
}

type instanceSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewInstanceSetInformer constructs a new informer for InstanceSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInstanceSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredInstanceSetInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredInstanceSetInformer constructs a new informer for InstanceSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInstanceSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha1().InstanceSets(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha1().InstanceSets(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha1().InstanceSets(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha1().InstanceSets(namespace).Watch(ctx, options)
			},
		},
		&apiworkloadsv1alpha1.InstanceSet{},
		resyncPeriod,
		indexers,
	)
}

func (f *instanceSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredInstanceSetInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *instanceSetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiworkloadsv1alpha1.InstanceSet{}, f.defaultInformer)
}

func (f *instanceSetInformer) Lister() workloadsv1alpha1.InstanceSetLister {
	return workloadsv1alpha1.NewInstanceSetLister(f.Informer().GetIndexer())
}
