/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1alpha2 "sigs.k8s.io/rbgs/api/workloads/v1alpha2"
	workloadsv1alpha2 "sigs.k8s.io/rbgs/client-go/applyconfiguration/workloads/v1alpha2"
	typedworkloadsv1alpha2 "sigs.k8s.io/rbgs/client-go/clientset/versioned/typed/workloads/v1alpha2"
)

// fakeClusterEngineRuntimeProfiles implements ClusterEngineRuntimeProfileInterface
type fakeClusterEngineRuntimeProfiles struct {
	*gentype.FakeClientWithListAndApply[*v1alpha2.ClusterEngineRuntimeProfile, *v1alpha2.ClusterEngineRuntimeProfileList, *workloadsv1alpha2.ClusterEngineRuntimeProfileApplyConfiguration]
	Fake *FakeWorkloadsV1alpha2
}

func newFakeClusterEngineRuntimeProfiles(fake *FakeWorkloadsV1alpha2, namespace string) typedworkloadsv1alpha2.ClusterEngineRuntimeProfileInterface {
	return &fakeClusterEngineRuntimeProfiles{
		gentype.NewFakeClientWithListAndApply[*v1alpha2.ClusterEngineRuntimeProfile, *v1alpha2.ClusterEngineRuntimeProfileList, *workloadsv1alpha2.ClusterEngineRuntimeProfileApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha2.SchemeGroupVersion.WithResource("clusterengineruntimeprofiles"),
			v1alpha2.SchemeGroupVersion.WithKind("ClusterEngineRuntimeProfile"),
			func() *v1alpha2.ClusterEngineRuntimeProfile { return &v1alpha2.ClusterEngineRuntimeProfile{} },
			func() *v1alpha2.ClusterEngineRuntimeProfileList { return &v1alpha2.ClusterEngineRuntimeProfileList{} },
			func(dst, src *v1alpha2.ClusterEngineRuntimeProfileList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha2.ClusterEngineRuntimeProfileList) []*v1alpha2.ClusterEngineRuntimeProfile {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha2.ClusterEngineRuntimeProfileList, items []*v1alpha2.ClusterEngineRuntimeProfile) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
