/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	context "context"

	autoscalingv1 "k8s.io/api/autoscaling/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
	testing "k8s.io/client-go/testing"
	v1alpha2 "sigs.k8s.io/rbgs/api/workloads/v1alpha2"
	workloadsv1alpha2 "sigs.k8s.io/rbgs/client-go/applyconfiguration/workloads/v1alpha2"
	typedworkloadsv1alpha2 "sigs.k8s.io/rbgs/client-go/clientset/versioned/typed/workloads/v1alpha2"
)

// fakeRoleInstanceSets implements RoleInstanceSetInterface
type fakeRoleInstanceSets struct {
	*gentype.FakeClientWithListAndApply[*v1alpha2.RoleInstanceSet, *v1alpha2.RoleInstanceSetList, *workloadsv1alpha2.RoleInstanceSetApplyConfiguration]
	Fake *FakeWorkloadsV1alpha2
}

func newFakeRoleInstanceSets(fake *FakeWorkloadsV1alpha2, namespace string) typedworkloadsv1alpha2.RoleInstanceSetInterface {
	return &fakeRoleInstanceSets{
		gentype.NewFakeClientWithListAndApply[*v1alpha2.RoleInstanceSet, *v1alpha2.RoleInstanceSetList, *workloadsv1alpha2.RoleInstanceSetApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha2.SchemeGroupVersion.WithResource("roleinstancesets"),
			v1alpha2.SchemeGroupVersion.WithKind("RoleInstanceSet"),
			func() *v1alpha2.RoleInstanceSet { return &v1alpha2.RoleInstanceSet{} },
			func() *v1alpha2.RoleInstanceSetList { return &v1alpha2.RoleInstanceSetList{} },
			func(dst, src *v1alpha2.RoleInstanceSetList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha2.RoleInstanceSetList) []*v1alpha2.RoleInstanceSet {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha2.RoleInstanceSetList, items []*v1alpha2.RoleInstanceSet) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}

// GetScale takes name of the roleInstanceSet, and returns the corresponding scale object, and an error if there is any.
func (c *fakeRoleInstanceSets) GetScale(ctx context.Context, roleInstanceSetName string, options v1.GetOptions) (result *autoscalingv1.Scale, err error) {
	emptyResult := &autoscalingv1.Scale{}
	obj, err := c.Fake.
		Invokes(testing.NewGetSubresourceActionWithOptions(c.Resource(), c.Namespace(), "scale", roleInstanceSetName, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*autoscalingv1.Scale), err
}

// UpdateScale takes the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *fakeRoleInstanceSets) UpdateScale(ctx context.Context, roleInstanceSetName string, scale *autoscalingv1.Scale, opts v1.UpdateOptions) (result *autoscalingv1.Scale, err error) {
	emptyResult := &autoscalingv1.Scale{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(c.Resource(), "scale", c.Namespace(), scale, opts), &autoscalingv1.Scale{})

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*autoscalingv1.Scale), err
}
