/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apiworkloadsv1alpha2 "sigs.k8s.io/rbgs/api/workloads/v1alpha2"
	versioned "sigs.k8s.io/rbgs/client-go/clientset/versioned"
	internalinterfaces "sigs.k8s.io/rbgs/client-go/informers/externalversions/internalinterfaces"
	workloadsv1alpha2 "sigs.k8s.io/rbgs/client-go/listers/workloads/v1alpha2"
)

// CoordinatedPolicyInformer provides access to a shared informer and lister for
// CoordinatedPolicies.
type CoordinatedPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() workloadsv1alpha2.CoordinatedPolicyLister
}

type coordinatedPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCoordinatedPolicyInformer constructs a new informer for CoordinatedPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCoordinatedPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCoordinatedPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCoordinatedPolicyInformer constructs a new informer for CoordinatedPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCoordinatedPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().CoordinatedPolicies(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().CoordinatedPolicies(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().CoordinatedPolicies(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().CoordinatedPolicies(namespace).Watch(ctx, options)
			},
		},
		&apiworkloadsv1alpha2.CoordinatedPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *coordinatedPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCoordinatedPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *coordinatedPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiworkloadsv1alpha2.CoordinatedPolicy{}, f.defaultInformer)
}

func (f *coordinatedPolicyInformer) Lister() workloadsv1alpha2.CoordinatedPolicyLister {
	return workloadsv1alpha2.NewCoordinatedPolicyLister(f.Informer().GetIndexer())
}
