/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	internalinterfaces "sigs.k8s.io/rbgs/client-go/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// CoordinatedPolicies returns a CoordinatedPolicyInformer.
	CoordinatedPolicies() CoordinatedPolicyInformer
	// RoleBasedGroups returns a RoleBasedGroupInformer.
	RoleBasedGroups() RoleBasedGroupInformer
	// RoleBasedGroupSets returns a RoleBasedGroupSetInformer.
	RoleBasedGroupSets() RoleBasedGroupSetInformer
	// RoleInstances returns a RoleInstanceInformer.
	RoleInstances() RoleInstanceInformer
	// RoleInstanceSets returns a RoleInstanceSetInformer.
	RoleInstanceSets() RoleInstanceSetInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// CoordinatedPolicies returns a CoordinatedPolicyInformer.
func (v *version) CoordinatedPolicies() CoordinatedPolicyInformer {
	return &coordinatedPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RoleBasedGroups returns a RoleBasedGroupInformer.
func (v *version) RoleBasedGroups() RoleBasedGroupInformer {
	return &roleBasedGroupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RoleBasedGroupSets returns a RoleBasedGroupSetInformer.
func (v *version) RoleBasedGroupSets() RoleBasedGroupSetInformer {
	return &roleBasedGroupSetInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RoleInstances returns a RoleInstanceInformer.
func (v *version) RoleInstances() RoleInstanceInformer {
	return &roleInstanceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RoleInstanceSets returns a RoleInstanceSetInformer.
func (v *version) RoleInstanceSets() RoleInstanceSetInformer {
	return &roleInstanceSetInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
