/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apiworkloadsv1alpha2 "sigs.k8s.io/rbgs/api/workloads/v1alpha2"
	versioned "sigs.k8s.io/rbgs/client-go/clientset/versioned"
	internalinterfaces "sigs.k8s.io/rbgs/client-go/informers/externalversions/internalinterfaces"
	workloadsv1alpha2 "sigs.k8s.io/rbgs/client-go/listers/workloads/v1alpha2"
)

// RoleInstanceInformer provides access to a shared informer and lister for
// RoleInstances.
type RoleInstanceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() workloadsv1alpha2.RoleInstanceLister
}

type roleInstanceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRoleInstanceInformer constructs a new informer for RoleInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRoleInstanceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRoleInstanceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRoleInstanceInformer constructs a new informer for RoleInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRoleInstanceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().RoleInstances(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().RoleInstances(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().RoleInstances(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().RoleInstances(namespace).Watch(ctx, options)
			},
		},
		&apiworkloadsv1alpha2.RoleInstance{},
		resyncPeriod,
		indexers,
	)
}

func (f *roleInstanceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRoleInstanceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *roleInstanceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiworkloadsv1alpha2.RoleInstance{}, f.defaultInformer)
}

func (f *roleInstanceInformer) Lister() workloadsv1alpha2.RoleInstanceLister {
	return workloadsv1alpha2.NewRoleInstanceLister(f.Informer().GetIndexer())
}
