/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	workloadsv1alpha1 "sigs.k8s.io/rbgs/api/workloads/v1alpha1"
)

// ClusterEngineRuntimeProfileLister helps list ClusterEngineRuntimeProfiles.
// All objects returned here must be treated as read-only.
type ClusterEngineRuntimeProfileLister interface {
	// List lists all ClusterEngineRuntimeProfiles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha1.ClusterEngineRuntimeProfile, err error)
	// ClusterEngineRuntimeProfiles returns an object that can list and get ClusterEngineRuntimeProfiles.
	ClusterEngineRuntimeProfiles(namespace string) ClusterEngineRuntimeProfileNamespaceLister
	ClusterEngineRuntimeProfileListerExpansion
}

// clusterEngineRuntimeProfileLister implements the ClusterEngineRuntimeProfileLister interface.
type clusterEngineRuntimeProfileLister struct {
	listers.ResourceIndexer[*workloadsv1alpha1.ClusterEngineRuntimeProfile]
}

// NewClusterEngineRuntimeProfileLister returns a new ClusterEngineRuntimeProfileLister.
func NewClusterEngineRuntimeProfileLister(indexer cache.Indexer) ClusterEngineRuntimeProfileLister {
	return &clusterEngineRuntimeProfileLister{listers.New[*workloadsv1alpha1.ClusterEngineRuntimeProfile](indexer, workloadsv1alpha1.Resource("clusterengineruntimeprofile"))}
}

// ClusterEngineRuntimeProfiles returns an object that can list and get ClusterEngineRuntimeProfiles.
func (s *clusterEngineRuntimeProfileLister) ClusterEngineRuntimeProfiles(namespace string) ClusterEngineRuntimeProfileNamespaceLister {
	return clusterEngineRuntimeProfileNamespaceLister{listers.NewNamespaced[*workloadsv1alpha1.ClusterEngineRuntimeProfile](s.ResourceIndexer, namespace)}
}

// ClusterEngineRuntimeProfileNamespaceLister helps list and get ClusterEngineRuntimeProfiles.
// All objects returned here must be treated as read-only.
type ClusterEngineRuntimeProfileNamespaceLister interface {
	// List lists all ClusterEngineRuntimeProfiles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha1.ClusterEngineRuntimeProfile, err error)
	// Get retrieves the ClusterEngineRuntimeProfile from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*workloadsv1alpha1.ClusterEngineRuntimeProfile, error)
	ClusterEngineRuntimeProfileNamespaceListerExpansion
}

// clusterEngineRuntimeProfileNamespaceLister implements the ClusterEngineRuntimeProfileNamespaceLister
// interface.
type clusterEngineRuntimeProfileNamespaceLister struct {
	listers.ResourceIndexer[*workloadsv1alpha1.ClusterEngineRuntimeProfile]
}
