/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	workloadsv1alpha1 "sigs.k8s.io/rbgs/api/workloads/v1alpha1"
)

// InstanceSetLister helps list InstanceSets.
// All objects returned here must be treated as read-only.
type InstanceSetLister interface {
	// List lists all InstanceSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha1.InstanceSet, err error)
	// InstanceSets returns an object that can list and get InstanceSets.
	InstanceSets(namespace string) InstanceSetNamespaceLister
	InstanceSetListerExpansion
}

// instanceSetLister implements the InstanceSetLister interface.
type instanceSetLister struct {
	listers.ResourceIndexer[*workloadsv1alpha1.InstanceSet]
}

// NewInstanceSetLister returns a new InstanceSetLister.
func NewInstanceSetLister(indexer cache.Indexer) InstanceSetLister {
	return &instanceSetLister{listers.New[*workloadsv1alpha1.InstanceSet](indexer, workloadsv1alpha1.Resource("instanceset"))}
}

// InstanceSets returns an object that can list and get InstanceSets.
func (s *instanceSetLister) InstanceSets(namespace string) InstanceSetNamespaceLister {
	return instanceSetNamespaceLister{listers.NewNamespaced[*workloadsv1alpha1.InstanceSet](s.ResourceIndexer, namespace)}
}

// InstanceSetNamespaceLister helps list and get InstanceSets.
// All objects returned here must be treated as read-only.
type InstanceSetNamespaceLister interface {
	// List lists all InstanceSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha1.InstanceSet, err error)
	// Get retrieves the InstanceSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*workloadsv1alpha1.InstanceSet, error)
	InstanceSetNamespaceListerExpansion
}

// instanceSetNamespaceLister implements the InstanceSetNamespaceLister
// interface.
type instanceSetNamespaceLister struct {
	listers.ResourceIndexer[*workloadsv1alpha1.InstanceSet]
}
