/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	workloadsv1alpha1 "sigs.k8s.io/rbgs/api/workloads/v1alpha1"
)

// RoleBasedGroupWarmUpLister helps list RoleBasedGroupWarmUps.
// All objects returned here must be treated as read-only.
type RoleBasedGroupWarmUpLister interface {
	// List lists all RoleBasedGroupWarmUps in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroupWarmUp, err error)
	// RoleBasedGroupWarmUps returns an object that can list and get RoleBasedGroupWarmUps.
	RoleBasedGroupWarmUps(namespace string) RoleBasedGroupWarmUpNamespaceLister
	RoleBasedGroupWarmUpListerExpansion
}

// roleBasedGroupWarmUpLister implements the RoleBasedGroupWarmUpLister interface.
type roleBasedGroupWarmUpLister struct {
	listers.ResourceIndexer[*workloadsv1alpha1.RoleBasedGroupWarmUp]
}

// NewRoleBasedGroupWarmUpLister returns a new RoleBasedGroupWarmUpLister.
func NewRoleBasedGroupWarmUpLister(indexer cache.Indexer) RoleBasedGroupWarmUpLister {
	return &roleBasedGroupWarmUpLister{listers.New[*workloadsv1alpha1.RoleBasedGroupWarmUp](indexer, workloadsv1alpha1.Resource("rolebasedgroupwarmup"))}
}

// RoleBasedGroupWarmUps returns an object that can list and get RoleBasedGroupWarmUps.
func (s *roleBasedGroupWarmUpLister) RoleBasedGroupWarmUps(namespace string) RoleBasedGroupWarmUpNamespaceLister {
	return roleBasedGroupWarmUpNamespaceLister{listers.NewNamespaced[*workloadsv1alpha1.RoleBasedGroupWarmUp](s.ResourceIndexer, namespace)}
}

// RoleBasedGroupWarmUpNamespaceLister helps list and get RoleBasedGroupWarmUps.
// All objects returned here must be treated as read-only.
type RoleBasedGroupWarmUpNamespaceLister interface {
	// List lists all RoleBasedGroupWarmUps in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroupWarmUp, err error)
	// Get retrieves the RoleBasedGroupWarmUp from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*workloadsv1alpha1.RoleBasedGroupWarmUp, error)
	RoleBasedGroupWarmUpNamespaceListerExpansion
}

// roleBasedGroupWarmUpNamespaceLister implements the RoleBasedGroupWarmUpNamespaceLister
// interface.
type roleBasedGroupWarmUpNamespaceLister struct {
	listers.ResourceIndexer[*workloadsv1alpha1.RoleBasedGroupWarmUp]
}
