/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	workloadsv1alpha1 "sigs.k8s.io/rbgs/api/workloads/v1alpha1"
)

// RoleBasedGroupScalingAdapterLister helps list RoleBasedGroupScalingAdapters.
// All objects returned here must be treated as read-only.
type RoleBasedGroupScalingAdapterLister interface {
	// List lists all RoleBasedGroupScalingAdapters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroupScalingAdapter, err error)
	// RoleBasedGroupScalingAdapters returns an object that can list and get RoleBasedGroupScalingAdapters.
	RoleBasedGroupScalingAdapters(namespace string) RoleBasedGroupScalingAdapterNamespaceLister
	RoleBasedGroupScalingAdapterListerExpansion
}

// roleBasedGroupScalingAdapterLister implements the RoleBasedGroupScalingAdapterLister interface.
type roleBasedGroupScalingAdapterLister struct {
	listers.ResourceIndexer[*workloadsv1alpha1.RoleBasedGroupScalingAdapter]
}

// NewRoleBasedGroupScalingAdapterLister returns a new RoleBasedGroupScalingAdapterLister.
func NewRoleBasedGroupScalingAdapterLister(indexer cache.Indexer) RoleBasedGroupScalingAdapterLister {
	return &roleBasedGroupScalingAdapterLister{listers.New[*workloadsv1alpha1.RoleBasedGroupScalingAdapter](indexer, workloadsv1alpha1.Resource("rolebasedgroupscalingadapter"))}
}

// RoleBasedGroupScalingAdapters returns an object that can list and get RoleBasedGroupScalingAdapters.
func (s *roleBasedGroupScalingAdapterLister) RoleBasedGroupScalingAdapters(namespace string) RoleBasedGroupScalingAdapterNamespaceLister {
	return roleBasedGroupScalingAdapterNamespaceLister{listers.NewNamespaced[*workloadsv1alpha1.RoleBasedGroupScalingAdapter](s.ResourceIndexer, namespace)}
}

// RoleBasedGroupScalingAdapterNamespaceLister helps list and get RoleBasedGroupScalingAdapters.
// All objects returned here must be treated as read-only.
type RoleBasedGroupScalingAdapterNamespaceLister interface {
	// List lists all RoleBasedGroupScalingAdapters in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroupScalingAdapter, err error)
	// Get retrieves the RoleBasedGroupScalingAdapter from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*workloadsv1alpha1.RoleBasedGroupScalingAdapter, error)
	RoleBasedGroupScalingAdapterNamespaceListerExpansion
}

// roleBasedGroupScalingAdapterNamespaceLister implements the RoleBasedGroupScalingAdapterNamespaceLister
// interface.
type roleBasedGroupScalingAdapterNamespaceLister struct {
	listers.ResourceIndexer[*workloadsv1alpha1.RoleBasedGroupScalingAdapter]
}
