/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	workloadsv1alpha1 "sigs.k8s.io/rbgs/api/workloads/v1alpha1"
)

// RoleBasedGroupSetLister helps list RoleBasedGroupSets.
// All objects returned here must be treated as read-only.
type RoleBasedGroupSetLister interface {
	// List lists all RoleBasedGroupSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroupSet, err error)
	// RoleBasedGroupSets returns an object that can list and get RoleBasedGroupSets.
	RoleBasedGroupSets(namespace string) RoleBasedGroupSetNamespaceLister
	RoleBasedGroupSetListerExpansion
}

// roleBasedGroupSetLister implements the RoleBasedGroupSetLister interface.
type roleBasedGroupSetLister struct {
	listers.ResourceIndexer[*workloadsv1alpha1.RoleBasedGroupSet]
}

// NewRoleBasedGroupSetLister returns a new RoleBasedGroupSetLister.
func NewRoleBasedGroupSetLister(indexer cache.Indexer) RoleBasedGroupSetLister {
	return &roleBasedGroupSetLister{listers.New[*workloadsv1alpha1.RoleBasedGroupSet](indexer, workloadsv1alpha1.Resource("rolebasedgroupset"))}
}

// RoleBasedGroupSets returns an object that can list and get RoleBasedGroupSets.
func (s *roleBasedGroupSetLister) RoleBasedGroupSets(namespace string) RoleBasedGroupSetNamespaceLister {
	return roleBasedGroupSetNamespaceLister{listers.NewNamespaced[*workloadsv1alpha1.RoleBasedGroupSet](s.ResourceIndexer, namespace)}
}

// RoleBasedGroupSetNamespaceLister helps list and get RoleBasedGroupSets.
// All objects returned here must be treated as read-only.
type RoleBasedGroupSetNamespaceLister interface {
	// List lists all RoleBasedGroupSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroupSet, err error)
	// Get retrieves the RoleBasedGroupSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*workloadsv1alpha1.RoleBasedGroupSet, error)
	RoleBasedGroupSetNamespaceListerExpansion
}

// roleBasedGroupSetNamespaceLister implements the RoleBasedGroupSetNamespaceLister
// interface.
type roleBasedGroupSetNamespaceLister struct {
	listers.ResourceIndexer[*workloadsv1alpha1.RoleBasedGroupSet]
}
