/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	autoscalingv1 "k8s.io/api/autoscaling/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	workloadsv1alpha1 "sigs.k8s.io/rbgs/api/workloads/v1alpha1"
	applyconfigurationworkloadsv1alpha1 "sigs.k8s.io/rbgs/client-go/applyconfiguration/workloads/v1alpha1"
	scheme "sigs.k8s.io/rbgs/client-go/clientset/versioned/scheme"
)

// InstanceSetsGetter has a method to return a InstanceSetInterface.
// A group's client should implement this interface.
type InstanceSetsGetter interface {
	InstanceSets(namespace string) InstanceSetInterface
}

// InstanceSetInterface has methods to work with InstanceSet resources.
type InstanceSetInterface interface {
	Create(ctx context.Context, instanceSet *workloadsv1alpha1.InstanceSet, opts v1.CreateOptions) (*workloadsv1alpha1.InstanceSet, error)
	Update(ctx context.Context, instanceSet *workloadsv1alpha1.InstanceSet, opts v1.UpdateOptions) (*workloadsv1alpha1.InstanceSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, instanceSet *workloadsv1alpha1.InstanceSet, opts v1.UpdateOptions) (*workloadsv1alpha1.InstanceSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadsv1alpha1.InstanceSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadsv1alpha1.InstanceSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadsv1alpha1.InstanceSet, err error)
	Apply(ctx context.Context, instanceSet *applyconfigurationworkloadsv1alpha1.InstanceSetApplyConfiguration, opts v1.ApplyOptions) (result *workloadsv1alpha1.InstanceSet, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, instanceSet *applyconfigurationworkloadsv1alpha1.InstanceSetApplyConfiguration, opts v1.ApplyOptions) (result *workloadsv1alpha1.InstanceSet, err error)
	GetScale(ctx context.Context, instanceSetName string, options v1.GetOptions) (*autoscalingv1.Scale, error)
	UpdateScale(ctx context.Context, instanceSetName string, scale *autoscalingv1.Scale, opts v1.UpdateOptions) (*autoscalingv1.Scale, error)

	InstanceSetExpansion
}

// instanceSets implements InstanceSetInterface
type instanceSets struct {
	*gentype.ClientWithListAndApply[*workloadsv1alpha1.InstanceSet, *workloadsv1alpha1.InstanceSetList, *applyconfigurationworkloadsv1alpha1.InstanceSetApplyConfiguration]
}

// newInstanceSets returns a InstanceSets
func newInstanceSets(c *WorkloadsV1alpha1Client, namespace string) *instanceSets {
	return &instanceSets{
		gentype.NewClientWithListAndApply[*workloadsv1alpha1.InstanceSet, *workloadsv1alpha1.InstanceSetList, *applyconfigurationworkloadsv1alpha1.InstanceSetApplyConfiguration](
			"instancesets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workloadsv1alpha1.InstanceSet { return &workloadsv1alpha1.InstanceSet{} },
			func() *workloadsv1alpha1.InstanceSetList { return &workloadsv1alpha1.InstanceSetList{} },
		),
	}
}

// GetScale takes name of the instanceSet, and returns the corresponding autoscalingv1.Scale object, and an error if there is any.
func (c *instanceSets) GetScale(ctx context.Context, instanceSetName string, options v1.GetOptions) (result *autoscalingv1.Scale, err error) {
	result = &autoscalingv1.Scale{}
	err = c.GetClient().Get().
		Namespace(c.GetNamespace()).
		Resource("instancesets").
		Name(instanceSetName).
		SubResource("scale").
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// UpdateScale takes the top resource name and the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *instanceSets) UpdateScale(ctx context.Context, instanceSetName string, scale *autoscalingv1.Scale, opts v1.UpdateOptions) (result *autoscalingv1.Scale, err error) {
	result = &autoscalingv1.Scale{}
	err = c.GetClient().Put().
		Namespace(c.GetNamespace()).
		Resource("instancesets").
		Name(instanceSetName).
		SubResource("scale").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(scale).
		Do(ctx).
		Into(result)
	return
}
