/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	workloadsv1alpha1 "sigs.k8s.io/rbgs/api/workloads/v1alpha1"
	applyconfigurationworkloadsv1alpha1 "sigs.k8s.io/rbgs/client-go/applyconfiguration/workloads/v1alpha1"
	scheme "sigs.k8s.io/rbgs/client-go/clientset/versioned/scheme"
)

// RoleBasedGroupsGetter has a method to return a RoleBasedGroupInterface.
// A group's client should implement this interface.
type RoleBasedGroupsGetter interface {
	RoleBasedGroups(namespace string) RoleBasedGroupInterface
}

// RoleBasedGroupInterface has methods to work with RoleBasedGroup resources.
type RoleBasedGroupInterface interface {
	Create(ctx context.Context, roleBasedGroup *workloadsv1alpha1.RoleBasedGroup, opts v1.CreateOptions) (*workloadsv1alpha1.RoleBasedGroup, error)
	Update(ctx context.Context, roleBasedGroup *workloadsv1alpha1.RoleBasedGroup, opts v1.UpdateOptions) (*workloadsv1alpha1.RoleBasedGroup, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, roleBasedGroup *workloadsv1alpha1.RoleBasedGroup, opts v1.UpdateOptions) (*workloadsv1alpha1.RoleBasedGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadsv1alpha1.RoleBasedGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadsv1alpha1.RoleBasedGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadsv1alpha1.RoleBasedGroup, err error)
	Apply(ctx context.Context, roleBasedGroup *applyconfigurationworkloadsv1alpha1.RoleBasedGroupApplyConfiguration, opts v1.ApplyOptions) (result *workloadsv1alpha1.RoleBasedGroup, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, roleBasedGroup *applyconfigurationworkloadsv1alpha1.RoleBasedGroupApplyConfiguration, opts v1.ApplyOptions) (result *workloadsv1alpha1.RoleBasedGroup, err error)
	RoleBasedGroupExpansion
}

// roleBasedGroups implements RoleBasedGroupInterface
type roleBasedGroups struct {
	*gentype.ClientWithListAndApply[*workloadsv1alpha1.RoleBasedGroup, *workloadsv1alpha1.RoleBasedGroupList, *applyconfigurationworkloadsv1alpha1.RoleBasedGroupApplyConfiguration]
}

// newRoleBasedGroups returns a RoleBasedGroups
func newRoleBasedGroups(c *WorkloadsV1alpha1Client, namespace string) *roleBasedGroups {
	return &roleBasedGroups{
		gentype.NewClientWithListAndApply[*workloadsv1alpha1.RoleBasedGroup, *workloadsv1alpha1.RoleBasedGroupList, *applyconfigurationworkloadsv1alpha1.RoleBasedGroupApplyConfiguration](
			"rolebasedgroups",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workloadsv1alpha1.RoleBasedGroup { return &workloadsv1alpha1.RoleBasedGroup{} },
			func() *workloadsv1alpha1.RoleBasedGroupList { return &workloadsv1alpha1.RoleBasedGroupList{} },
		),
	}
}
