/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	workloadsv1alpha2 "sigs.k8s.io/rbgs/api/workloads/v1alpha2"
	applyconfigurationworkloadsv1alpha2 "sigs.k8s.io/rbgs/client-go/applyconfiguration/workloads/v1alpha2"
	scheme "sigs.k8s.io/rbgs/client-go/clientset/versioned/scheme"
)

// RoleInstancesGetter has a method to return a RoleInstanceInterface.
// A group's client should implement this interface.
type RoleInstancesGetter interface {
	RoleInstances(namespace string) RoleInstanceInterface
}

// RoleInstanceInterface has methods to work with RoleInstance resources.
type RoleInstanceInterface interface {
	Create(ctx context.Context, roleInstance *workloadsv1alpha2.RoleInstance, opts v1.CreateOptions) (*workloadsv1alpha2.RoleInstance, error)
	Update(ctx context.Context, roleInstance *workloadsv1alpha2.RoleInstance, opts v1.UpdateOptions) (*workloadsv1alpha2.RoleInstance, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, roleInstance *workloadsv1alpha2.RoleInstance, opts v1.UpdateOptions) (*workloadsv1alpha2.RoleInstance, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadsv1alpha2.RoleInstance, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadsv1alpha2.RoleInstanceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadsv1alpha2.RoleInstance, err error)
	Apply(ctx context.Context, roleInstance *applyconfigurationworkloadsv1alpha2.RoleInstanceApplyConfiguration, opts v1.ApplyOptions) (result *workloadsv1alpha2.RoleInstance, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, roleInstance *applyconfigurationworkloadsv1alpha2.RoleInstanceApplyConfiguration, opts v1.ApplyOptions) (result *workloadsv1alpha2.RoleInstance, err error)
	RoleInstanceExpansion
}

// roleInstances implements RoleInstanceInterface
type roleInstances struct {
	*gentype.ClientWithListAndApply[*workloadsv1alpha2.RoleInstance, *workloadsv1alpha2.RoleInstanceList, *applyconfigurationworkloadsv1alpha2.RoleInstanceApplyConfiguration]
}

// newRoleInstances returns a RoleInstances
func newRoleInstances(c *WorkloadsV1alpha2Client, namespace string) *roleInstances {
	return &roleInstances{
		gentype.NewClientWithListAndApply[*workloadsv1alpha2.RoleInstance, *workloadsv1alpha2.RoleInstanceList, *applyconfigurationworkloadsv1alpha2.RoleInstanceApplyConfiguration](
			"roleinstances",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workloadsv1alpha2.RoleInstance { return &workloadsv1alpha2.RoleInstance{} },
			func() *workloadsv1alpha2.RoleInstanceList { return &workloadsv1alpha2.RoleInstanceList{} },
		),
	}
}
