/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	workloadsv1alpha2 "sigs.k8s.io/rbgs/api/workloads/v1alpha2"
	applyconfigurationworkloadsv1alpha2 "sigs.k8s.io/rbgs/client-go/applyconfiguration/workloads/v1alpha2"
	scheme "sigs.k8s.io/rbgs/client-go/clientset/versioned/scheme"
)

// RoleBasedGroupSetsGetter has a method to return a RoleBasedGroupSetInterface.
// A group's client should implement this interface.
type RoleBasedGroupSetsGetter interface {
	RoleBasedGroupSets(namespace string) RoleBasedGroupSetInterface
}

// RoleBasedGroupSetInterface has methods to work with RoleBasedGroupSet resources.
type RoleBasedGroupSetInterface interface {
	Create(ctx context.Context, roleBasedGroupSet *workloadsv1alpha2.RoleBasedGroupSet, opts v1.CreateOptions) (*workloadsv1alpha2.RoleBasedGroupSet, error)
	Update(ctx context.Context, roleBasedGroupSet *workloadsv1alpha2.RoleBasedGroupSet, opts v1.UpdateOptions) (*workloadsv1alpha2.RoleBasedGroupSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, roleBasedGroupSet *workloadsv1alpha2.RoleBasedGroupSet, opts v1.UpdateOptions) (*workloadsv1alpha2.RoleBasedGroupSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadsv1alpha2.RoleBasedGroupSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadsv1alpha2.RoleBasedGroupSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadsv1alpha2.RoleBasedGroupSet, err error)
	Apply(ctx context.Context, roleBasedGroupSet *applyconfigurationworkloadsv1alpha2.RoleBasedGroupSetApplyConfiguration, opts v1.ApplyOptions) (result *workloadsv1alpha2.RoleBasedGroupSet, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, roleBasedGroupSet *applyconfigurationworkloadsv1alpha2.RoleBasedGroupSetApplyConfiguration, opts v1.ApplyOptions) (result *workloadsv1alpha2.RoleBasedGroupSet, err error)
	RoleBasedGroupSetExpansion
}

// roleBasedGroupSets implements RoleBasedGroupSetInterface
type roleBasedGroupSets struct {
	*gentype.ClientWithListAndApply[*workloadsv1alpha2.RoleBasedGroupSet, *workloadsv1alpha2.RoleBasedGroupSetList, *applyconfigurationworkloadsv1alpha2.RoleBasedGroupSetApplyConfiguration]
}

// newRoleBasedGroupSets returns a RoleBasedGroupSets
func newRoleBasedGroupSets(c *WorkloadsV1alpha2Client, namespace string) *roleBasedGroupSets {
	return &roleBasedGroupSets{
		gentype.NewClientWithListAndApply[*workloadsv1alpha2.RoleBasedGroupSet, *workloadsv1alpha2.RoleBasedGroupSetList, *applyconfigurationworkloadsv1alpha2.RoleBasedGroupSetApplyConfiguration](
			"rolebasedgroupsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workloadsv1alpha2.RoleBasedGroupSet { return &workloadsv1alpha2.RoleBasedGroupSet{} },
			func() *workloadsv1alpha2.RoleBasedGroupSetList { return &workloadsv1alpha2.RoleBasedGroupSetList{} },
		),
	}
}
