/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	workloadsv1alpha2 "sigs.k8s.io/rbgs/api/workloads/v1alpha2"
)

// CustomComponentsPatternApplyConfiguration represents a declarative configuration of the CustomComponentsPattern type for use
// with apply.
type CustomComponentsPatternApplyConfiguration struct {
	Components          []InstanceComponentApplyConfiguration  `json:"components,omitempty"`
	RestartPolicy       *workloadsv1alpha2.RestartPolicyType   `json:"restartPolicy,omitempty"`
	RestartPolicyConfig *RestartPolicyConfigApplyConfiguration `json:"restartPolicyConfig,omitempty"`
}

// CustomComponentsPatternApplyConfiguration constructs a declarative configuration of the CustomComponentsPattern type for use with
// apply.
func CustomComponentsPattern() *CustomComponentsPatternApplyConfiguration {
	return &CustomComponentsPatternApplyConfiguration{}
}

// WithComponents adds the given value to the Components field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Components field.
func (b *CustomComponentsPatternApplyConfiguration) WithComponents(values ...*InstanceComponentApplyConfiguration) *CustomComponentsPatternApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithComponents")
		}
		b.Components = append(b.Components, *values[i])
	}
	return b
}

// WithRestartPolicy sets the RestartPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestartPolicy field is set to the value of the last call.
func (b *CustomComponentsPatternApplyConfiguration) WithRestartPolicy(value workloadsv1alpha2.RestartPolicyType) *CustomComponentsPatternApplyConfiguration {
	b.RestartPolicy = &value
	return b
}

// WithRestartPolicyConfig sets the RestartPolicyConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestartPolicyConfig field is set to the value of the last call.
func (b *CustomComponentsPatternApplyConfiguration) WithRestartPolicyConfig(value *RestartPolicyConfigApplyConfiguration) *CustomComponentsPatternApplyConfiguration {
	b.RestartPolicyConfig = value
	return b
}
