/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	intstr "k8s.io/apimachinery/pkg/util/intstr"
	workloadsv1alpha2 "sigs.k8s.io/rbgs/api/workloads/v1alpha2"
)

// GroupSetRolloutStrategyApplyConfiguration represents a declarative configuration of the GroupSetRolloutStrategy type for use
// with apply.
type GroupSetRolloutStrategyApplyConfiguration struct {
	Type           *workloadsv1alpha2.GroupUpdateStrategyType `json:"type,omitempty"`
	Partition      *intstr.IntOrString                        `json:"partition,omitempty"`
	MaxUnavailable *intstr.IntOrString                        `json:"maxUnavailable,omitempty"`
	MaxSurge       *intstr.IntOrString                        `json:"maxSurge,omitempty"`
	Paused         *bool                                      `json:"paused,omitempty"`
}

// GroupSetRolloutStrategyApplyConfiguration constructs a declarative configuration of the GroupSetRolloutStrategy type for use with
// apply.
func GroupSetRolloutStrategy() *GroupSetRolloutStrategyApplyConfiguration {
	return &GroupSetRolloutStrategyApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *GroupSetRolloutStrategyApplyConfiguration) WithType(value workloadsv1alpha2.GroupUpdateStrategyType) *GroupSetRolloutStrategyApplyConfiguration {
	b.Type = &value
	return b
}

// WithPartition sets the Partition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Partition field is set to the value of the last call.
func (b *GroupSetRolloutStrategyApplyConfiguration) WithPartition(value intstr.IntOrString) *GroupSetRolloutStrategyApplyConfiguration {
	b.Partition = &value
	return b
}

// WithMaxUnavailable sets the MaxUnavailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxUnavailable field is set to the value of the last call.
func (b *GroupSetRolloutStrategyApplyConfiguration) WithMaxUnavailable(value intstr.IntOrString) *GroupSetRolloutStrategyApplyConfiguration {
	b.MaxUnavailable = &value
	return b
}

// WithMaxSurge sets the MaxSurge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxSurge field is set to the value of the last call.
func (b *GroupSetRolloutStrategyApplyConfiguration) WithMaxSurge(value intstr.IntOrString) *GroupSetRolloutStrategyApplyConfiguration {
	b.MaxSurge = &value
	return b
}

// WithPaused sets the Paused field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Paused field is set to the value of the last call.
func (b *GroupSetRolloutStrategyApplyConfiguration) WithPaused(value bool) *GroupSetRolloutStrategyApplyConfiguration {
	b.Paused = &value
	return b
}
