/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/client-go/applyconfigurations/core/v1"
	workloadsv1alpha2 "sigs.k8s.io/rbgs/api/workloads/v1alpha2"
)

// LeaderWorkerPatternApplyConfiguration represents a declarative configuration of the LeaderWorkerPattern type for use
// with apply.
type LeaderWorkerPatternApplyConfiguration struct {
	Size                             *int32 `json:"size,omitempty"`
	TemplateSourceApplyConfiguration `json:",inline"`
	LeaderTemplatePatch              *runtime.RawExtension                           `json:"leaderTemplatePatch,omitempty"`
	WorkerTemplatePatch              *runtime.RawExtension                           `json:"workerTemplatePatch,omitempty"`
	SharedServiceSelection           *workloadsv1alpha2.SharedServiceSelectionPolicy `json:"sharedServiceSelection,omitempty"`
	RestartPolicy                    *workloadsv1alpha2.RestartPolicyType            `json:"restartPolicy,omitempty"`
	RestartPolicyConfig              *RestartPolicyConfigApplyConfiguration          `json:"restartPolicyConfig,omitempty"`
}

// LeaderWorkerPatternApplyConfiguration constructs a declarative configuration of the LeaderWorkerPattern type for use with
// apply.
func LeaderWorkerPattern() *LeaderWorkerPatternApplyConfiguration {
	return &LeaderWorkerPatternApplyConfiguration{}
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *LeaderWorkerPatternApplyConfiguration) WithSize(value int32) *LeaderWorkerPatternApplyConfiguration {
	b.Size = &value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *LeaderWorkerPatternApplyConfiguration) WithTemplate(value *v1.PodTemplateSpecApplyConfiguration) *LeaderWorkerPatternApplyConfiguration {
	b.TemplateSourceApplyConfiguration.Template = value
	return b
}

// WithTemplateRef sets the TemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateRef field is set to the value of the last call.
func (b *LeaderWorkerPatternApplyConfiguration) WithTemplateRef(value *TemplateRefApplyConfiguration) *LeaderWorkerPatternApplyConfiguration {
	b.TemplateSourceApplyConfiguration.TemplateRef = value
	return b
}

// WithLeaderTemplatePatch sets the LeaderTemplatePatch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaderTemplatePatch field is set to the value of the last call.
func (b *LeaderWorkerPatternApplyConfiguration) WithLeaderTemplatePatch(value runtime.RawExtension) *LeaderWorkerPatternApplyConfiguration {
	b.LeaderTemplatePatch = &value
	return b
}

// WithWorkerTemplatePatch sets the WorkerTemplatePatch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkerTemplatePatch field is set to the value of the last call.
func (b *LeaderWorkerPatternApplyConfiguration) WithWorkerTemplatePatch(value runtime.RawExtension) *LeaderWorkerPatternApplyConfiguration {
	b.WorkerTemplatePatch = &value
	return b
}

// WithSharedServiceSelection sets the SharedServiceSelection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SharedServiceSelection field is set to the value of the last call.
func (b *LeaderWorkerPatternApplyConfiguration) WithSharedServiceSelection(value workloadsv1alpha2.SharedServiceSelectionPolicy) *LeaderWorkerPatternApplyConfiguration {
	b.SharedServiceSelection = &value
	return b
}

// WithRestartPolicy sets the RestartPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestartPolicy field is set to the value of the last call.
func (b *LeaderWorkerPatternApplyConfiguration) WithRestartPolicy(value workloadsv1alpha2.RestartPolicyType) *LeaderWorkerPatternApplyConfiguration {
	b.RestartPolicy = &value
	return b
}

// WithRestartPolicyConfig sets the RestartPolicyConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestartPolicyConfig field is set to the value of the last call.
func (b *LeaderWorkerPatternApplyConfiguration) WithRestartPolicyConfig(value *RestartPolicyConfigApplyConfiguration) *LeaderWorkerPatternApplyConfiguration {
	b.RestartPolicyConfig = value
	return b
}
