/*
Copyright 2025 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// PatternApplyConfiguration represents a declarative configuration of the Pattern type for use
// with apply.
type PatternApplyConfiguration struct {
	StandalonePattern       *StandalonePatternApplyConfiguration       `json:"standalonePattern,omitempty"`
	LeaderWorkerPattern     *LeaderWorkerPatternApplyConfiguration     `json:"leaderWorkerPattern,omitempty"`
	CustomComponentsPattern *CustomComponentsPatternApplyConfiguration `json:"customComponentsPattern,omitempty"`
}

// PatternApplyConfiguration constructs a declarative configuration of the Pattern type for use with
// apply.
func Pattern() *PatternApplyConfiguration {
	return &PatternApplyConfiguration{}
}

// WithStandalonePattern sets the StandalonePattern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StandalonePattern field is set to the value of the last call.
func (b *PatternApplyConfiguration) WithStandalonePattern(value *StandalonePatternApplyConfiguration) *PatternApplyConfiguration {
	b.StandalonePattern = value
	return b
}

// WithLeaderWorkerPattern sets the LeaderWorkerPattern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaderWorkerPattern field is set to the value of the last call.
func (b *PatternApplyConfiguration) WithLeaderWorkerPattern(value *LeaderWorkerPatternApplyConfiguration) *PatternApplyConfiguration {
	b.LeaderWorkerPattern = value
	return b
}

// WithCustomComponentsPattern sets the CustomComponentsPattern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomComponentsPattern field is set to the value of the last call.
func (b *PatternApplyConfiguration) WithCustomComponentsPattern(value *CustomComponentsPatternApplyConfiguration) *PatternApplyConfiguration {
	b.CustomComponentsPattern = value
	return b
}
