/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	workloadsv1alpha2 "sigs.k8s.io/rbgs/api/workloads/v1alpha2"
)

// RestartPolicyConfigApplyConfiguration represents a declarative configuration of the RestartPolicyConfig type for use
// with apply.
type RestartPolicyConfigApplyConfiguration struct {
	Type             *workloadsv1alpha2.RestartPolicyType `json:"type,omitempty"`
	BaseDelaySeconds *int32                               `json:"baseDelaySeconds,omitempty"`
	MaxDelaySeconds  *int32                               `json:"maxDelaySeconds,omitempty"`
}

// RestartPolicyConfigApplyConfiguration constructs a declarative configuration of the RestartPolicyConfig type for use with
// apply.
func RestartPolicyConfig() *RestartPolicyConfigApplyConfiguration {
	return &RestartPolicyConfigApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *RestartPolicyConfigApplyConfiguration) WithType(value workloadsv1alpha2.RestartPolicyType) *RestartPolicyConfigApplyConfiguration {
	b.Type = &value
	return b
}

// WithBaseDelaySeconds sets the BaseDelaySeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseDelaySeconds field is set to the value of the last call.
func (b *RestartPolicyConfigApplyConfiguration) WithBaseDelaySeconds(value int32) *RestartPolicyConfigApplyConfiguration {
	b.BaseDelaySeconds = &value
	return b
}

// WithMaxDelaySeconds sets the MaxDelaySeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxDelaySeconds field is set to the value of the last call.
func (b *RestartPolicyConfigApplyConfiguration) WithMaxDelaySeconds(value int32) *RestartPolicyConfigApplyConfiguration {
	b.MaxDelaySeconds = &value
	return b
}
