/*
Copyright 2025 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// RoleBasedGroupSpecApplyConfiguration represents a declarative configuration of the RoleBasedGroupSpec type for use
// with apply.
type RoleBasedGroupSpecApplyConfiguration struct {
	Roles         []RoleSpecApplyConfiguration     `json:"roles,omitempty"`
	RoleTemplates []RoleTemplateApplyConfiguration `json:"roleTemplates,omitempty"`
}

// RoleBasedGroupSpecApplyConfiguration constructs a declarative configuration of the RoleBasedGroupSpec type for use with
// apply.
func RoleBasedGroupSpec() *RoleBasedGroupSpecApplyConfiguration {
	return &RoleBasedGroupSpecApplyConfiguration{}
}

// WithRoles adds the given value to the Roles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Roles field.
func (b *RoleBasedGroupSpecApplyConfiguration) WithRoles(values ...*RoleSpecApplyConfiguration) *RoleBasedGroupSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRoles")
		}
		b.Roles = append(b.Roles, *values[i])
	}
	return b
}

// WithRoleTemplates adds the given value to the RoleTemplates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RoleTemplates field.
func (b *RoleBasedGroupSpecApplyConfiguration) WithRoleTemplates(values ...*RoleTemplateApplyConfiguration) *RoleBasedGroupSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRoleTemplates")
		}
		b.RoleTemplates = append(b.RoleTemplates, *values[i])
	}
	return b
}
