/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// RoleInstanceStatusApplyConfiguration represents a declarative configuration of the RoleInstanceStatus type for use
// with apply.
type RoleInstanceStatusApplyConfiguration struct {
	ObservedGeneration *int64                                          `json:"observedGeneration,omitempty"`
	Conditions         []RoleInstanceConditionApplyConfiguration       `json:"conditions,omitempty"`
	ComponentStatuses  []RoleInstanceComponentStatusApplyConfiguration `json:"componentStatuses,omitempty"`
	LabelSelector      *string                                         `json:"labelSelector,omitempty"`
	CurrentRevision    *string                                         `json:"currentRevision,omitempty"`
	UpdateRevision     *string                                         `json:"updateRevision,omitempty"`
	CollisionCount     *int32                                          `json:"collisionCount,omitempty"`
}

// RoleInstanceStatusApplyConfiguration constructs a declarative configuration of the RoleInstanceStatus type for use with
// apply.
func RoleInstanceStatus() *RoleInstanceStatusApplyConfiguration {
	return &RoleInstanceStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *RoleInstanceStatusApplyConfiguration) WithObservedGeneration(value int64) *RoleInstanceStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *RoleInstanceStatusApplyConfiguration) WithConditions(values ...*RoleInstanceConditionApplyConfiguration) *RoleInstanceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithComponentStatuses adds the given value to the ComponentStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ComponentStatuses field.
func (b *RoleInstanceStatusApplyConfiguration) WithComponentStatuses(values ...*RoleInstanceComponentStatusApplyConfiguration) *RoleInstanceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithComponentStatuses")
		}
		b.ComponentStatuses = append(b.ComponentStatuses, *values[i])
	}
	return b
}

// WithLabelSelector sets the LabelSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelSelector field is set to the value of the last call.
func (b *RoleInstanceStatusApplyConfiguration) WithLabelSelector(value string) *RoleInstanceStatusApplyConfiguration {
	b.LabelSelector = &value
	return b
}

// WithCurrentRevision sets the CurrentRevision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentRevision field is set to the value of the last call.
func (b *RoleInstanceStatusApplyConfiguration) WithCurrentRevision(value string) *RoleInstanceStatusApplyConfiguration {
	b.CurrentRevision = &value
	return b
}

// WithUpdateRevision sets the UpdateRevision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdateRevision field is set to the value of the last call.
func (b *RoleInstanceStatusApplyConfiguration) WithUpdateRevision(value string) *RoleInstanceStatusApplyConfiguration {
	b.UpdateRevision = &value
	return b
}

// WithCollisionCount sets the CollisionCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollisionCount field is set to the value of the last call.
func (b *RoleInstanceStatusApplyConfiguration) WithCollisionCount(value int32) *RoleInstanceStatusApplyConfiguration {
	b.CollisionCount = &value
	return b
}
