/*
Copyright 2025 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
	constants "sigs.k8s.io/rbgs/api/workloads/constants"
)

// RoleInstanceSetSpecApplyConfiguration represents a declarative configuration of the RoleInstanceSetSpec type for use
// with apply.
type RoleInstanceSetSpecApplyConfiguration struct {
	Replicas             *int32                                           `json:"replicas,omitempty"`
	Selector             *v1.LabelSelectorApplyConfiguration              `json:"selector,omitempty"`
	RoleInstanceTemplate *RoleInstanceTemplateApplyConfiguration          `json:"roleInstanceTemplate,omitempty"`
	PodManagementPolicy  *constants.PodManagementPolicyType               `json:"podManagementPolicy,omitempty"`
	ScaleStrategy        *RoleInstanceSetScaleStrategyApplyConfiguration  `json:"scaleStrategy,omitempty"`
	UpdateStrategy       *RoleInstanceSetUpdateStrategyApplyConfiguration `json:"updateStrategy,omitempty"`
	RevisionHistoryLimit *int32                                           `json:"revisionHistoryLimit,omitempty"`
	MinReadySeconds      *int32                                           `json:"minReadySeconds,omitempty"`
	Lifecycle            *RoleInstanceSetLifecycleApplyConfiguration      `json:"lifecycle,omitempty"`
}

// RoleInstanceSetSpecApplyConfiguration constructs a declarative configuration of the RoleInstanceSetSpec type for use with
// apply.
func RoleInstanceSetSpec() *RoleInstanceSetSpecApplyConfiguration {
	return &RoleInstanceSetSpecApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *RoleInstanceSetSpecApplyConfiguration) WithReplicas(value int32) *RoleInstanceSetSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *RoleInstanceSetSpecApplyConfiguration) WithSelector(value *v1.LabelSelectorApplyConfiguration) *RoleInstanceSetSpecApplyConfiguration {
	b.Selector = value
	return b
}

// WithRoleInstanceTemplate sets the RoleInstanceTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RoleInstanceTemplate field is set to the value of the last call.
func (b *RoleInstanceSetSpecApplyConfiguration) WithRoleInstanceTemplate(value *RoleInstanceTemplateApplyConfiguration) *RoleInstanceSetSpecApplyConfiguration {
	b.RoleInstanceTemplate = value
	return b
}

// WithPodManagementPolicy sets the PodManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodManagementPolicy field is set to the value of the last call.
func (b *RoleInstanceSetSpecApplyConfiguration) WithPodManagementPolicy(value constants.PodManagementPolicyType) *RoleInstanceSetSpecApplyConfiguration {
	b.PodManagementPolicy = &value
	return b
}

// WithScaleStrategy sets the ScaleStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScaleStrategy field is set to the value of the last call.
func (b *RoleInstanceSetSpecApplyConfiguration) WithScaleStrategy(value *RoleInstanceSetScaleStrategyApplyConfiguration) *RoleInstanceSetSpecApplyConfiguration {
	b.ScaleStrategy = value
	return b
}

// WithUpdateStrategy sets the UpdateStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdateStrategy field is set to the value of the last call.
func (b *RoleInstanceSetSpecApplyConfiguration) WithUpdateStrategy(value *RoleInstanceSetUpdateStrategyApplyConfiguration) *RoleInstanceSetSpecApplyConfiguration {
	b.UpdateStrategy = value
	return b
}

// WithRevisionHistoryLimit sets the RevisionHistoryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RevisionHistoryLimit field is set to the value of the last call.
func (b *RoleInstanceSetSpecApplyConfiguration) WithRevisionHistoryLimit(value int32) *RoleInstanceSetSpecApplyConfiguration {
	b.RevisionHistoryLimit = &value
	return b
}

// WithMinReadySeconds sets the MinReadySeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinReadySeconds field is set to the value of the last call.
func (b *RoleInstanceSetSpecApplyConfiguration) WithMinReadySeconds(value int32) *RoleInstanceSetSpecApplyConfiguration {
	b.MinReadySeconds = &value
	return b
}

// WithLifecycle sets the Lifecycle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Lifecycle field is set to the value of the last call.
func (b *RoleInstanceSetSpecApplyConfiguration) WithLifecycle(value *RoleInstanceSetLifecycleApplyConfiguration) *RoleInstanceSetSpecApplyConfiguration {
	b.Lifecycle = value
	return b
}
