/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	workloadsv1alpha2 "sigs.k8s.io/rbgs/api/workloads/v1alpha2"
)

// RoleInstanceTemplateApplyConfiguration represents a declarative configuration of the RoleInstanceTemplate type for use
// with apply.
type RoleInstanceTemplateApplyConfiguration struct {
	RoleInstanceSpecApplyConfiguration `json:",inline"`
}

// RoleInstanceTemplateApplyConfiguration constructs a declarative configuration of the RoleInstanceTemplate type for use with
// apply.
func RoleInstanceTemplate() *RoleInstanceTemplateApplyConfiguration {
	return &RoleInstanceTemplateApplyConfiguration{}
}

// WithComponents adds the given value to the Components field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Components field.
func (b *RoleInstanceTemplateApplyConfiguration) WithComponents(values ...*RoleInstanceComponentApplyConfiguration) *RoleInstanceTemplateApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithComponents")
		}
		b.RoleInstanceSpecApplyConfiguration.Components = append(b.RoleInstanceSpecApplyConfiguration.Components, *values[i])
	}
	return b
}

// WithReadyPolicy sets the ReadyPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyPolicy field is set to the value of the last call.
func (b *RoleInstanceTemplateApplyConfiguration) WithReadyPolicy(value workloadsv1alpha2.RoleInstanceReadyPolicyType) *RoleInstanceTemplateApplyConfiguration {
	b.RoleInstanceSpecApplyConfiguration.ReadyPolicy = &value
	return b
}

// WithRestartPolicy sets the RestartPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestartPolicy field is set to the value of the last call.
func (b *RoleInstanceTemplateApplyConfiguration) WithRestartPolicy(value workloadsv1alpha2.RoleInstanceRestartPolicyType) *RoleInstanceTemplateApplyConfiguration {
	b.RoleInstanceSpecApplyConfiguration.RestartPolicy = &value
	return b
}

// WithReadinessGates adds the given value to the ReadinessGates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ReadinessGates field.
func (b *RoleInstanceTemplateApplyConfiguration) WithReadinessGates(values ...*RoleInstanceReadinessGateApplyConfiguration) *RoleInstanceTemplateApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithReadinessGates")
		}
		b.RoleInstanceSpecApplyConfiguration.ReadinessGates = append(b.RoleInstanceSpecApplyConfiguration.ReadinessGates, *values[i])
	}
	return b
}
