/*
Copyright 2025 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// RoleInstanceComponentStatusApplyConfiguration represents a declarative configuration of the RoleInstanceComponentStatus type for use
// with apply.
type RoleInstanceComponentStatusApplyConfiguration struct {
	Name                 *string `json:"name,omitempty"`
	Size                 *int32  `json:"size,omitempty"`
	ReadyReplicas        *int32  `json:"readyReplicas,omitempty"`
	UpdatedReplicas      *int32  `json:"updatedReplicas,omitempty"`
	ScheduledReplicas    *int32  `json:"scheduledReplicas,omitempty"`
	AvailableReplicas    *int32  `json:"availableReplicas,omitempty"`
	UpdatedReadyReplicas *int32  `json:"updatedReadyReplicas,omitempty"`
}

// RoleInstanceComponentStatusApplyConfiguration constructs a declarative configuration of the RoleInstanceComponentStatus type for use with
// apply.
func RoleInstanceComponentStatus() *RoleInstanceComponentStatusApplyConfiguration {
	return &RoleInstanceComponentStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RoleInstanceComponentStatusApplyConfiguration) WithName(value string) *RoleInstanceComponentStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *RoleInstanceComponentStatusApplyConfiguration) WithSize(value int32) *RoleInstanceComponentStatusApplyConfiguration {
	b.Size = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *RoleInstanceComponentStatusApplyConfiguration) WithReadyReplicas(value int32) *RoleInstanceComponentStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithUpdatedReplicas sets the UpdatedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedReplicas field is set to the value of the last call.
func (b *RoleInstanceComponentStatusApplyConfiguration) WithUpdatedReplicas(value int32) *RoleInstanceComponentStatusApplyConfiguration {
	b.UpdatedReplicas = &value
	return b
}

// WithScheduledReplicas sets the ScheduledReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScheduledReplicas field is set to the value of the last call.
func (b *RoleInstanceComponentStatusApplyConfiguration) WithScheduledReplicas(value int32) *RoleInstanceComponentStatusApplyConfiguration {
	b.ScheduledReplicas = &value
	return b
}

// WithAvailableReplicas sets the AvailableReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableReplicas field is set to the value of the last call.
func (b *RoleInstanceComponentStatusApplyConfiguration) WithAvailableReplicas(value int32) *RoleInstanceComponentStatusApplyConfiguration {
	b.AvailableReplicas = &value
	return b
}

// WithUpdatedReadyReplicas sets the UpdatedReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedReadyReplicas field is set to the value of the last call.
func (b *RoleInstanceComponentStatusApplyConfiguration) WithUpdatedReadyReplicas(value int32) *RoleInstanceComponentStatusApplyConfiguration {
	b.UpdatedReadyReplicas = &value
	return b
}
