/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// RollingUpdateCoordinationStrategyApplyConfiguration represents a declarative configuration of the RollingUpdateCoordinationStrategy type for use
// with apply.
type RollingUpdateCoordinationStrategyApplyConfiguration struct {
	MaxSkew        *intstr.IntOrString `json:"maxSkew,omitempty"`
	Partition      *intstr.IntOrString `json:"partition,omitempty"`
	MaxUnavailable *intstr.IntOrString `json:"maxUnavailable,omitempty"`
}

// RollingUpdateCoordinationStrategyApplyConfiguration constructs a declarative configuration of the RollingUpdateCoordinationStrategy type for use with
// apply.
func RollingUpdateCoordinationStrategy() *RollingUpdateCoordinationStrategyApplyConfiguration {
	return &RollingUpdateCoordinationStrategyApplyConfiguration{}
}

// WithMaxSkew sets the MaxSkew field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxSkew field is set to the value of the last call.
func (b *RollingUpdateCoordinationStrategyApplyConfiguration) WithMaxSkew(value intstr.IntOrString) *RollingUpdateCoordinationStrategyApplyConfiguration {
	b.MaxSkew = &value
	return b
}

// WithPartition sets the Partition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Partition field is set to the value of the last call.
func (b *RollingUpdateCoordinationStrategyApplyConfiguration) WithPartition(value intstr.IntOrString) *RollingUpdateCoordinationStrategyApplyConfiguration {
	b.Partition = &value
	return b
}

// WithMaxUnavailable sets the MaxUnavailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxUnavailable field is set to the value of the last call.
func (b *RollingUpdateCoordinationStrategyApplyConfiguration) WithMaxUnavailable(value intstr.IntOrString) *RollingUpdateCoordinationStrategyApplyConfiguration {
	b.MaxUnavailable = &value
	return b
}
