# Default values for rbgs-controller.

replicaCount: 2

image:
  repository: rolebasedgroup/rbgs-controller
  pullPolicy: IfNotPresent
  tag: v0.6.0-5390c07

imagePullSecrets: []

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

resources:
  limits:
    cpu: 1000m
    memory: 1536Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

crdUpgrade:
  # Whether to enable CRD Upgrader Job (runs before install/upgrade)
  enabled: true
  # Time-to-live (TTL) for crd-upgrade jobs after completion. Default is 259200 seconds (3 days).
  ttlSecondsAfterFinished: 259200
  # CRD Upgrader image configuration
  repository: rolebasedgroup/rbgs-upgrade-crd
  tag: v0.6.0-5390c07
  imagePullPolicy: IfNotPresent
  # Tolerations for CRD Upgrader Job pod
  tolerations:
    - operator: Exists
  # Node selector for CRD Upgrader Job pod
  nodeSelector: {}
