# Default values for rbgs-controller.

replicaCount: 2

image:
  repository: rolebasedgroup/rbgs-controller
  pullPolicy: IfNotPresent
  tag: v0.7.0-47b2681

imagePullSecrets: []

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

resources:
  limits:
    cpu: 1000m
    memory: 1536Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

# Gang scheduling scheduler name configuration.
# Supported values: scheduler-plugins, volcano
# Defaults to scheduler-plugins.
schedulerName: scheduler-plugins

crdUpgrade:
  # Whether to enable CRD Upgrader Job (runs before install/upgrade)
  enabled: true
  # Time-to-live (TTL) for crd-upgrade jobs after completion. Default is 259200 seconds (3 days).
  ttlSecondsAfterFinished: 259200
  # CRD Upgrader image configuration
  repository: rolebasedgroup/rbgs-upgrade-crd
  tag: v0.7.0-47b2681
  imagePullPolicy: IfNotPresent
  # Tolerations for CRD Upgrader Job pod
  tolerations:
    - operator: Exists
  # Node selector for CRD Upgrader Job pod
  nodeSelector: {}

# Port allocator configuration for dynamic port allocation to pods.
portAllocator:
  # Whether to enable the port allocator feature.
  enabled: false
  # Port allocation strategy. Supported values: random.
  strategy: random
  # The starting port number of the allocatable port range.
  startPort: 30000
  # The size of the allocatable port range.
  portRange: 5000
