apiVersion: workloads.x-k8s.io/v1alpha1
kind: RoleBasedGroup
metadata:
  name: nginx-cluster
  annotations:
    rolebasedgroup.workloads.x-k8s.io/exclusive-topology: "kubernetes.io/hostname"
spec:
  roles:
    - name: leader
      replicas: 1
      template:
        # disable exclusive topology for role
        # metadata:
        #   annotations:
        #     rolebasedgroup.workloads.x-k8s.io/disable-exclusive-topology: "true"
        spec:
          containers:
            - name: nginx-leader
              image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/nginx:1.14.1-8.6
              ports:
                - containerPort: 80

    - name: worker
      replicas: 1
      workload:
        apiVersion: apps/v1
        kind: Deployment
      template:
        spec:
          containers:
            - name: nginx-worker
              image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/nginx:1.14.1-8.6
              ports:
                - containerPort: 8080

    - name: lws
      replicas: 1
      workload:
        apiVersion: leaderworkerset.x-k8s.io/v1
        kind: LeaderWorkerSet
      leaderWorkerSet:
        size: 1
      template:
        spec:
          containers:
            - name: nginx
              image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/nginx:1.14.1-8.6

