/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "sigs.k8s.io/rbgs/api/workloads/v1alpha1"
	workloadsv1alpha1 "sigs.k8s.io/rbgs/client-go/applyconfiguration/workloads/v1alpha1"
	typedworkloadsv1alpha1 "sigs.k8s.io/rbgs/client-go/clientset/versioned/typed/workloads/v1alpha1"
)

// fakeRoleBasedGroups implements RoleBasedGroupInterface
type fakeRoleBasedGroups struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.RoleBasedGroup, *v1alpha1.RoleBasedGroupList, *workloadsv1alpha1.RoleBasedGroupApplyConfiguration]
	Fake *FakeWorkloadsV1alpha1
}

func newFakeRoleBasedGroups(fake *FakeWorkloadsV1alpha1, namespace string) typedworkloadsv1alpha1.RoleBasedGroupInterface {
	return &fakeRoleBasedGroups{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.RoleBasedGroup, *v1alpha1.RoleBasedGroupList, *workloadsv1alpha1.RoleBasedGroupApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("rolebasedgroups"),
			v1alpha1.SchemeGroupVersion.WithKind("RoleBasedGroup"),
			func() *v1alpha1.RoleBasedGroup { return &v1alpha1.RoleBasedGroup{} },
			func() *v1alpha1.RoleBasedGroupList { return &v1alpha1.RoleBasedGroupList{} },
			func(dst, src *v1alpha1.RoleBasedGroupList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.RoleBasedGroupList) []*v1alpha1.RoleBasedGroup {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.RoleBasedGroupList, items []*v1alpha1.RoleBasedGroup) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
