/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	context "context"

	autoscalingv1 "k8s.io/api/autoscaling/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
	testing "k8s.io/client-go/testing"
	v1alpha1 "sigs.k8s.io/rbgs/api/workloads/v1alpha1"
	workloadsv1alpha1 "sigs.k8s.io/rbgs/client-go/applyconfiguration/workloads/v1alpha1"
	typedworkloadsv1alpha1 "sigs.k8s.io/rbgs/client-go/clientset/versioned/typed/workloads/v1alpha1"
)

// fakeInstanceSets implements InstanceSetInterface
type fakeInstanceSets struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.InstanceSet, *v1alpha1.InstanceSetList, *workloadsv1alpha1.InstanceSetApplyConfiguration]
	Fake *FakeWorkloadsV1alpha1
}

func newFakeInstanceSets(fake *FakeWorkloadsV1alpha1, namespace string) typedworkloadsv1alpha1.InstanceSetInterface {
	return &fakeInstanceSets{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.InstanceSet, *v1alpha1.InstanceSetList, *workloadsv1alpha1.InstanceSetApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("instancesets"),
			v1alpha1.SchemeGroupVersion.WithKind("InstanceSet"),
			func() *v1alpha1.InstanceSet { return &v1alpha1.InstanceSet{} },
			func() *v1alpha1.InstanceSetList { return &v1alpha1.InstanceSetList{} },
			func(dst, src *v1alpha1.InstanceSetList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.InstanceSetList) []*v1alpha1.InstanceSet {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.InstanceSetList, items []*v1alpha1.InstanceSet) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}

// GetScale takes name of the instanceSet, and returns the corresponding scale object, and an error if there is any.
func (c *fakeInstanceSets) GetScale(ctx context.Context, instanceSetName string, options v1.GetOptions) (result *autoscalingv1.Scale, err error) {
	emptyResult := &autoscalingv1.Scale{}
	obj, err := c.Fake.
		Invokes(testing.NewGetSubresourceActionWithOptions(c.Resource(), c.Namespace(), "scale", instanceSetName, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*autoscalingv1.Scale), err
}

// UpdateScale takes the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *fakeInstanceSets) UpdateScale(ctx context.Context, instanceSetName string, scale *autoscalingv1.Scale, opts v1.UpdateOptions) (result *autoscalingv1.Scale, err error) {
	emptyResult := &autoscalingv1.Scale{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(c.Resource(), "scale", c.Namespace(), scale, opts), &autoscalingv1.Scale{})

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*autoscalingv1.Scale), err
}
