apiVersion: workloads.x-k8s.io/v1alpha1
kind: RoleBasedGroup
metadata:
  name: sglang-pd-with-mooncake-demo
spec:
  roles:
    - name: mooncake-master
      replicas: 1
      template:
        spec:
          containers:
            - name: master
              image: lmsysorg/sglang:v0.5.5
              env:
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
              command:
                - mooncake_master
              args:
                - --enable_http_metadata_server=true
                - --eviction_high_watermark_ratio=0.95
                - --rpc_address
                - $(POD_IP)
                - --rpc_port
                - "50051"
                - --http_metadata_server_host
                - $(POD_IP)
                - --http_metadata_server_port
                - "8080"
                - --metrics_port
                - "9003"
              ports:
                - containerPort: 8080
                  name: http
              readinessProbe:
                initialDelaySeconds: 10
                periodSeconds: 10
                tcpSocket:
                  port: 8080
    - name: mooncake-store
      replicas: 3
      dependencies: [ "mooncake-master" ]
      annotations:
        instance.rolebasedgroup.workloads.x-k8s.io/pattern: Stateless
      workload:
        apiVersion: workloads.x-k8s.io/v1alpha1
        kind: InstanceSet
      template:
        spec:
          containers:
            - name: store
              image: lmsysorg/sglang:v0.5.5
              env:
                - name: MOONCAKE_MASTER
                  value: "s-sglang-pd-with-mooncake-demo-mooncake-master:50051"
                - name: MOONCAKE_TE_META_DATA_SERVER
                  value: "http://s-sglang-pd-with-mooncake-demo-mooncake-master:8080/metadata"
                - name: MOONCAKE_GLOBAL_SEGMENT_SIZE
                  value: "45gb" #Configure the cache size per replica on demand.
                - name: MOONCAKE_LOCAL_BUFFER_SIZE
                  value: "0"
                - name: MOONCAKE_PROTOCOL
                  value: "rdma"
                - name: MOONCAKE_DEVICE
                  value: ""
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
              command:
                - python
                - -m
                - mooncake.mooncake_store_service
              resources:
                limits:
                  memory: "50Gi"
                  rdma/hca: 1
                requests:
                  memory: "50Gi"
                  rdma/hca: 1
    - name: router
      dependencies: [ "prefill", "decode" ]
      replicas: 1
      template:
        spec:
          containers:
            - name: schedule
              image: lmsysorg/sglang:v0.5.5
              command:
                - python3
                - -m
                - sglang_router.launch_router
                - --pd-disaggregation
                - --prefill
                - http://sglang-pd-with-mooncake-demo-prefill-0.s-sglang-pd-with-mooncake-demo-prefill:8000
                - --decode
                - http://sglang-pd-with-mooncake-demo-decode-0.s-sglang-pd-with-mooncake-demo-decode:8000
                - --host
                - 0.0.0.0
                - --port
                - "8000"
    - name: prefill
      replicas: 1
      dependencies: [ "mooncake-master" ]
      template:
        spec:
          volumes:
            - name: model
              persistentVolumeClaim:
                claimName: qwen3-235b
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 30Gi
          containers:
            - name: sglang-prefill
              image: lmsysorg/sglang:v0.5.5
              imagePullPolicy: Always
              env:
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                - name: MOONCAKE_MASTER
                  value: "s-sglang-pd-with-mooncake-demo-mooncake-master:50051"
                - name: MOONCAKE_TE_META_DATA_SERVER
                  value: "http://s-sglang-pd-with-mooncake-demo-mooncake-master:8080/metadata"
                - name: MOONCAKE_PROTOCOL
                  value: "rdma"
                - name: MOONCAKE_DEVICE
                  value: ""
                - name: MOONCAKE_GLOBAL_SEGMENT_SIZE
                  value: "10gb" #Configure the cache size per replica on demand.
                - name: MOONCAKE_LOCAL_BUFFER_SIZE
                  value: "16777216"
                - name: MC_MS_AUTO_DISC
                  value: "0"
              command:
                - python3
                - -m
                - sglang.launch_server
                - --model-path
                - /models/Qwen3
                - --tp
                - "4"
                - --enable-metrics
                - --disaggregation-mode
                - prefill
                - --disaggregation-transfer-backend
                - mooncake
                - --port
                - "8000"
                - --host
                - $(POD_IP)
                - --enable-torch-compile
                - --enable-hierarchical-cache
                - --hicache-storage-backend
                - mooncake
              ports:
                - containerPort: 8000
                  name: http
              readinessProbe:
                initialDelaySeconds: 30
                periodSeconds: 10
                tcpSocket:
                  port: 8000
              resources:
                limits:
                  nvidia.com/gpu: "4"
                  rdma/hca: 1
                  memory: "100Gi"
                requests:
                  nvidia.com/gpu: "4"
                  rdma/hca: 1
                  memory: "100Gi"
              volumeMounts:
                - mountPath: /models/Qwen3
                  name: model
                - mountPath: /dev/shm
                  name: dshm
    - name: decode
      replicas: 1
      dependencies: [ "mooncake-master" ]
      template:
        spec:
          volumes:
            - name: model
              persistentVolumeClaim:
                claimName: qwen3-235b
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 30Gi
          containers:
            - name: sglang-decode
              image: lmsysorg/sglang:v0.5.5
              imagePullPolicy: Always
              env:
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
              command:
                - python3
                - -m
                - sglang.launch_server
                - --model-path
                - /models/Qwen3
                - --tp
                - "4"
                - --enable-metrics
                - --disaggregation-mode
                - decode
                - --port
                - "8000"
                - --host
                - $(POD_IP)
              ports:
                - containerPort: 8000
                  name: http
              readinessProbe:
                initialDelaySeconds: 30
                periodSeconds: 10
                tcpSocket:
                  port: 8000
              resources:
                limits:
                  nvidia.com/gpu: "4"
                  rdma/hca: 1
                requests:
                  nvidia.com/gpu: "4"
                  rdma/hca: 1
              volumeMounts:
                - mountPath: /models/Qwen3
                  name: model
                - mountPath: /dev/shm
                  name: dshm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sglang-pd-with-mooncake-demo
  name: sglang-pd-with-mooncake-demo
  namespace: default
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: sglang-pd-with-mooncake-demo
    rolebasedgroup.workloads.x-k8s.io/role: router
  type: ClusterIP
