apiVersion: workloads.x-k8s.io/v1alpha1
kind: Instance
metadata:
  name: nginx-instance
  namespace: default
spec:
  readyPolicy: AllPodReady
  components:
    - name: leader
      size: 1
      template:
        spec:
          containers:
            - name: nginx
              image: nginx:1.28.0
              ports:
                - containerPort: 8080
    - name: worker
      size: 2
      template:
        spec:
          containers:
            - name: nginx
              image: nginx:1.28.0
              ports:
                - containerPort: 8080
